### PR TITLE
List own comments

### PR DESCRIPTION
**Pull request by infinite-persistence**
## Test
KP » Settings » Account » Comments

## Issue
Closes [#5146 Show all own comments](https://github.com/lbryio/lbry-desktop/issues/5146)

## Known issues
<strike>The total number of comments that Commentron reports vs. what it returns, can be different.  Checking with Mark/Tom.</strike> Fixed

### CODE REVIEW

**Comment by infinite-persistence** [comment]
### cd2f3d2 to bac26bc
Commentron now requires authorization for this action.

**Comment by tzarebczan** [comment]
Don't love the placement of where this is avaialble, but probably the best bet for now. 

Checking with Beamer on a sorting issue, otherwise it looks good!

**Comment by infinite-persistence** [comment]
#### bac26bc to 05f2aed
- Add i18n strings
- Rebased

**Comment by tzarebczan** [comment]
There's a new sorting method (5 I think - check DMs) to remove pins. 

Can we make the comment clickable or linkable?

**Comment by infinite-persistence** [comment]
05f2aed to 48247cb
- Mobile: removed indent; reduced claim thumbnail size.
- Remove automatic pinning when fetching.
- Clicking on the claim (left side) now links to the comment directly.  The comment (right side) remains unclickable due to:
    - I find hard to copy/paste parts of the comment if the entire section is clickable.
    - But I did try and couldn't get `NavLink` to work with `Comment` -- it causes lots of renders and blinking.  Maybe re-visit this next time, but for now use the left-side to click?
        - Also considered adding a "View comment" button at the lower-right of each row, but that made the page busier than it is already.

**Pull request merged**
