### PR TITLE
Enhance audio metadata access using music-metadata-browser

### PR DESCRIPTION
**Pull request by Borewit**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other

## Fixes

Issue Number: N/A

## Related

* #1824 Feature Request: It'll Be Nice To See Visualizations/Album Art When Playing Audio Files

## What is the current behavior?
Able to extract metadata from: MP3, FLAC, M4A

## What is the new behavior?
Able to extract metadata from: MP3, FLAC, M4A, WAV, Ogg (Vorbis, Opus), WavPack, DSDIFF, DSF, WMA (pretty much every audio format)

## Other information
[music-metadata-browser](https://github.com/Borewit/music-metadata-browser) is based on [music-metadata](https://github.com/borewit/music-metadata) which is the most advanced and [popular](https://npmcharts.com/compare/music-metadata,jsmediatags,musicmetadata,node-id3,music-metadata-browser,mp3-parser,browser-id3-writer,id3-parser,mp4-parser,parse-audio-metadata?start=600) metadata parser available today. Simular apps using music-metadata: [webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop), [webamp](https://webamp.org/), [volumio](https://volumio.org/), [mediacenterjs](https://github.com/jansmolders86/mediacenterjs) and many more.

I am looking forward to work with you. Please let know it you have specific challenges in this area I maybe able to help you with.

### CODE REVIEW

**Comment by seanyesmunt** [comment]
This is awesome! Thanks for the PR!

I'll be able to review this tomorrow.

**Comment by Borewit** [comment]
You could consider capturing the metadata at the node/server side (the main process). This has the advantage you could re-use the audio track already downloaded instead of setting up a second download channel.

Even retrieving metadata while downloading is an option. This is done in [webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop) to display metadata while _streaming in_ the torrent.

The format metadata like bit-rate, sample-rate etc. maybe also interesting to visualize.

**Comment by seanyesmunt** [comment]
@Borewit This looks pretty straight forward but I am not able to get audio working with it. Once the file is downloaded I'm able to see the cover art/track info, but no sound. Streaming is broken too, but that is its own issue that I am going to fix soon.

You can check out lbry://@mime#649f5d766f6ca2db1be249b09e164ffe52939751 for a few different audio file types.

You probably noticed but our new audio player is ~a little~ pretty broken right now. Perhaps you would be interested in finishing that work up? @tzarebczan told me he reached out to you. I'd love to chat more with you! Our video/audio player experience is definitely an area that could use a lot of improvement.

Thanks again for your first PR! 🙂

**Comment by seanyesmunt** [comment]
@Borewit I'm going to close this for now, but I've brought it into my own branch to mess around with. I don't think we are going to ship this new audio player right now anyway so we have some time. Excited to talk more about this when you get more time! I'll reach out on discord if I have any questions.

**Comment by Borewit** [comment]
Alright

**Pull request closed without merging**
