### PR TITLE
Patch for comicbook viewer

### PR DESCRIPTION
**Pull request by btzr-io**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [x] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Changes
- [ ] Web view / embed / share ( ? )
- [x] Fix: error opening certain files with special characters in name https://github.com/lbryio/lbry-desktop/issues/2777
- [x] Fix: cbz/cbr file page shows download button first, and then viewer after download #4141

## Other information
This or similar files should not longer fail to load:
``` lbry://144BlackestNightby01GreenLantern43Prologuecbz#b```

> Note this changes can be use on any `nonstream` files like `3D` to be displayed on the web, using the new stream hooks to get a blob.

### CODE REVIEW

**Comment by btzr-io** [comment]
How can I bypass this error / warning?
https://github.com/dearrrfish/preprocess-loader/issues/14

**Comment by btzr-io** [comment]
I tried to test it on the web version but it's just stuck on loading, probably because of the file size ?
Anyway it should be really easy to enable now, just remove `COMIC` from this line:

https://github.com/lbryio/lbry-desktop/blob/c35388fd0e62ba05091181903cd1670f769c81c1/ui/constants/file_render_modes.js#L31

**Comment by btzr-io** [comment]
Now I can't load any content on the dev server 🙃 
I'll need help testing on the web version if that's a feature that should be added

**Comment by seanyesmunt** [comment]
Thanks for this @btzr-io!

I'll mess around with trying this on web with different file types, but I think this can be merged before that. Can you rebase and add a changelog entry?

**Comment by btzr-io** [comment]
Ok, done.

**Comment by seanyesmunt** [comment]
@btzr-io There is still a conflict. Can you rebase?

**Comment by btzr-io** [comment]
@seanyesmunt ok, hmm I don't see any conflicts on the `github` UI 🤔

**Comment by seanyesmunt** [comment]
Hm. Ok don't worry about it. I'll check it out and merge in a little bit.

**Comment by btzr-io** [comment]
@seanyesmunt I think I fixed the conflicts

**Pull request merged**
