### PR TITLE
Save media position in video viewer

### PR DESCRIPTION
**Pull request by jeffslofish**
PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #2775

## What is the current behavior?
Videos start playing at beginning of the video.

## What is the new behavior?
Video position is saved when being played. If a previously viewed video is played again, it starts at the saved location.

### CODE REVIEW

**Comment by jeffslofish** [comment]
I abandoned my previous pull request (#4098) and created this clean one with the changes you wanted.

**Comment by seanyesmunt** [comment]
Nice! I like the minimal changes. Do you notice any issues writing that value so often? If so, maybe it should only be written every x seconds or so? Or when the video stops?

**Comment by jeffslofish** [comment]
I didn't notice any issue, but perhaps there would be on some devices. Let me see what I can do to make it write less often (hopefully just once)...

**Comment by jeffslofish** [comment]
I updated the code to only save the media position on pause or dispose (in case they leave the page without stopping the video first) instead of every timeupdate event. This should help out performance and save the position in the majority of cases.

**Pull request merged**
