### PR TITLE
#1772 - add Reverse Order & Use System/Location Time/Date

### PR DESCRIPTION
**Pull request by TiagoKaska**
add Reverse Order & Use System/Location Time/Date

### CODE REVIEW

**Comment by seanyesmunt** [comment]
@TiagoKaska Thanks for the PR! 🙂 

Do you know if there is a time when we wouldn't want to use `moment.locale(remote.app.getLocale())`?

If so, maybe we should move that line to `src/renderer/index.js` to keep things consistent.

**Comment by TiagoKaska** [comment]
@seanyesmunt I can't remove console.log ? in file src/renderer/index.js :

21:20  error    Absolute imports should come before relative imports  import/first
 69:9   warning  Unexpected console statement                          no-console
161:7   warning  Unexpected console statement                          no-console
164:7   warning  Unexpected console statement                          no-console
167:7   warning  Unexpected console statement                          no-console

**Comment by seanyesmunt** [comment]
@TiagoKaska We can keep those. Maybe add `/* eslint-disable no-console */` at the top of the file, then `/* eslint-enable no-console */` at the bottom. That should disable it just for that file.

**Comment by seanyesmunt** [comment]
@TiagoKaska Great. Do you know if that affects any other dates? Maybe on the history page?

I'll give it a test too. Can you also add a [changelog](https://github.com/lbryio/lbry-desktop/blob/src/CHANGELOG) udpate?

**Comment by TiagoKaska** [comment]
> @seanyesmunt I noticed that it affects all the dates where the moment is used

**Comment by seanyesmunt** [comment]
I think it's ok, just tested and it looks fine. I'm guessing we should have been doing this already for dates that use moment. I'm going to merge this.

**Comment by seanyesmunt** [comment]
@TiagoKaska thanks for the contribution! If you haven't already, checkout our [contributing] (https://github.com/lbryio/lbry-desktop/blob/master/CONTRIBUTING.md) guide if you haven't yet (sorry I didn't send this to you when you first opened your PR.

Can we send you[ LBC in appreciation for your work](https://lbry.io/faq/appreciation)?

**Comment by TiagoKaska** [comment]
thanks @seanyesmunt 👍 
my wallet address bMEgg2vVvMi93MMdKdYH1uVKk7XfMVTYxm

**Comment by alyssaoc** [comment]
@TiagoKaska Please follow the instructions at https://lbry.io/faq/appreciation, so we can sen you an appreciation. Thank you

**Pull request merged**
