### PR TITLE
Fix gap between video player and background 

### PR DESCRIPTION
**Pull request by btzr-io**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes
Fix gap between video player and background #3025

### CODE REVIEW

**Comment by btzr-io** [comment]
Still need to test this on a different pc or monitor.
For some reason I cant reproduce this on my current pc :upside_down_face:

**Comment by seanyesmunt** [comment]
I haven't been able to reproduce this bug on my computer so I'm not sure if this fixes it. @tzarebczan Could you test this?

**Comment by tzarebczan** [comment]
Yep, seems to fix it here! Nice job @btzr-io

**Comment by tzarebczan** [comment]
@btzr-io, thanks for the PR! Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the contribution? 

Also, we're giving away some [Hacktoberfest](https://lbry.com/news/hacktoberfest-2019) bonuses and goodies for this month. We'll get it all figured out after you shoot us an email after this is reviewed/merged.

**Pull request merged**
