### PR TITLE
[WIP] Revive old audio viewer

### PR DESCRIPTION
**Pull request by Borewit**
Related to issue number: #2757

Restores the "old" audio player.

Start playing audio automatically after the audio viewer is activated.

----

I think the visualization leaves room for improvement. I propose to:
- Keep displaying the main album cover
- Improve the visualization of the metadata:
   - artist
   - track title
   - track number, if applicable
   - maybe the album the track is part of  
- Display audio format: container, codec, bit-rate
- Cut out, the milk-drop visualization, maybe a small spectrum-analyzer instead

To attract artists releasing their music to LBRY, I think it would interesting to offer the possibility to release albums.

### CODE REVIEW

**Comment by seanyesmunt** [comment]
Awesome!! 🙂

Excited to check this out! Probably won't get to it until tonight or tomorrow. I'll let you know!

**Comment by tzarebczan** [comment]
@Borewit once this gets merged, make sure to send us an email so we can show you some [appreciation](https://lbry.com/faq/appreciation) for the contribution.

**Comment by Borewit** [comment]
ToDo:
* [ ]  Address: if an audio file is playing and you navigate to another one, the old one continues to play and theres no way to get the new one to play without refreshing the page.
* [ ] Get rid of all the `me` and just use `this`.
* style cleanup:
  * [ ] It's hard to tell where to seek
  * [ ] there are some issues when no metadata is found
  * [ ] metadata text is a little hard to read

**Comment by tzarebczan** [comment]
@Borewit do you still plan to finish this up? We'd very much [appreciate it!](https://lbry.com/faq/appreciation)

**Comment by Borewit** [comment]
> @Borewit do you still plan to finish this up?

Not sure if I will finish it. I contribute almost every day a bit on open source coding. To get something some that they gives me satisfaction. I have to say this is a bit of steep hill for me, I am not very experienced with React, it I pick up I first have to get everything in sync, debugging is tricky, and sometimes after a few runs the app leaves me in the dark, maybe corrupted profile.

To compensate my lack of experience, behind the scenes I approached some talented front-end developers, experienced in writing audio players. Developers I know from my user community of [music-metadata](https://github.com/borewit/music-metadata), yet so far no luck someone jumping on it.

I created this issue initially to revive the old player. A saw that as a starting point, I am honestly not big fan of the look an feel. I agree with the all point of improvement given by @seanyesmunt: clear progress indicator, clear control, easy readable track metadata.

Imagine all of that is put in. The only thing what is left is the Milkdrop. I am not a fan of it, not in this application. I would say metadata, cover art. Between the buttons and progress bar, maybe a subtle spectrum analyzer line dancing. Subtle, but a proper high tech one, one with frequency scaled in octaves, how human perceive notes (@hvianna is a specialist [in this area](https://hvianna.github.io/audioMotion.js/public/)).

This step feels at the moment as bit to big for me.

**Comment by hvianna** [comment]
>Subtle, but a proper high tech one, one with frequency scaled in octaves, how human perceive notes (@hvianna is a specialist [in this area](https://hvianna.github.io/audioMotion.js/public/)).
> 

I recently released the spectrum analyzer I designed for audioMotion as a [standalone module](https://github.com/hvianna/audioMotion-analyzer) which can be integrated into other JavaScript applications.

Here's a [demo of multiple instances](https://hvianna.github.io/audioMotion-analyzer/demo/multi.html) of the analyzer running simultaneously, with different visualization options.

I don't have any experience with React though, and my code may be still a little messy, but I'm willing to keep improving it. Maybe it's a start? :)

**Comment by tzarebczan** [comment]
@Borewit thank you for the reply - no worries! Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the work thus far? 

@hvianna please feel free to take a stab if you are interested. We tip in LBC for contributions :)

**Comment by seanyesmunt** [comment]
I'm going to close this for now. I think eventually we will re-open this to finish it up but it's not a high priority for now. Thanks for sharing those links @hvianna ! I'll check them out 🙂

**Pull request closed without merging**
