### PR TITLE
Inf-scroll: (1) Reset to top (2) Fix "page vs. results" being out of sync

### LINKED ISSUE #2669: Page does not restore to top when navigating new tags
## The Issue
If you scroll down one of the trending lists and then click a tag, it goes to the tag page but not to the top of it. It may cut off the header and some results. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### PR DESCRIPTION
**Pull request by infinite-persistence**
## PR Type
- [x] Bugfix
1. Fixes #2669 `Page does not restore to top when navigating new tags.`
   To replicate the issue, you will need to first visit the tag and scroll down, move to another tag, then re-visit the first tag. Querying new tags won't show the issue. 

2. "Encountered children with the same key" error (duplicate entries shown).
(Also reported by https://github.com/lbryio/lbry-desktop/issues/4367#issuecomment-645449206)

## Code changes
1. Ignore the history if it's a new query (i.e. explicitly clicked). The BACK history will still behave as normal (doesn't reset to top).

2. Previously, the `page` variable will continue to increment as you scroll and stay within the page (e.g. Trending vs New, or clicked another Tag). As you move between queries, we hit a scenario where `page` is significantly under or over the latest retrieved `claimSearchResult.length`. This messes up the rest of the code.

   Fix by correcting the value of `page` according to the current `claimSearchResult.length` when necessary.

## Notes
The new function introduced might be a bit inefficient.

### CODE REVIEW

**Comment by seanyesmunt** [comment]
Resetting to the top of the page when clicking on a tag works, but it seems like there is something weird happening with scroll restoration when clicking "back".

I think it only happens when clicking a tag, scroll restoration after navigating to the file page seems to work well. Can you take a look at that?

**Comment by infinite-persistence** [comment]
I only found the following issue during my testing.  As it is also present in today's code, I thought of looking at that  separately later.
Is it the same as what you are seeing, or a totally different sequence? 

1. Reload
2. Click TagA, scroll down
3. Click TagB, scroll down
4. Click TagC, scroll down
5. Click `back` = TagC's previous scroll location retained ✅
6. Click `back` = TagB's previous scroll location retained ✅
7. Click `forward` = scroll location is lost.

I'll re-visit the above in this PR, and any other bad sequence that you know of.  Let me know if you can still remember the sequence.

**Comment by infinite-persistence** [comment]
@seanyesmunt, I still couldn't find any glitches with `back`, although I did find other issues that are present in `0.46.2`.  I'm interested to look at those as well, but I think it's cleaner to start another PR for that.

Other issues found but also present in `0.46.2`:
1. `forward` doesn't restore the scrolling position (because it has been popped, so no data to restore with).
2. Clicking on the same tag 5 times results in 5 pushes, so there will be 5 `back` that are no-op.  (perhaps this is the behavior that you saw?)
3. 4408 `Inf-scroll: doClaimSearch() sometimes returns duplicates, causing scrolling problems.`

**Comment by seanyesmunt** [comment]
Yeah I'm not sure exactly what I was seeing. I think this is still an improvement over what we currently have so I think it's good to merge.

**Pull request merged**
