### PR TITLE
Fixing inline videos in comments

### PR DESCRIPTION
**Pull request by DaniNz**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: https://github.com/lbryio/lbry-desktop/issues/5384

## What is the current behavior?
Editing a comment that has an embed in the playing state, doesn't hide the player

## What is the new behavior?
Editing a comment that has an embed in the playing state, does hide the player

### CODE REVIEW

**Comment by DispatchCommit** [comment]
Adding a type declaration for the new prop `closeInlinePlayer` in in the type declaration here: 
https://github.com/lbryio/lbry-desktop/blob/be51d9f5712ec1fc8df83616db4c0593536b91cf/ui/component/comment/view.jsx#L24

should fix that linting error. Thanks for the quick fix!

**Review by DispatchCommit — CHANGES_REQUESTED** [review]
Adding a type declaration for the new prop `closeInlinePlayer` in in the type declaration here: 
https://github.com/lbryio/lbry-desktop/blob/be51d9f5712ec1fc8df83616db4c0593536b91cf/ui/component/comment/view.jsx#L24

should fix that linting error. Thanks for the quick fix!

**Comment by DaniNz** [comment]
Oh sorry about that. I just sent the changes.

**Comment by seanyesmunt** [comment]
@DaniNz Thank you for this PR! It looks great 🙂

**Pull request merged**
