### PR TITLE
Add custom quality selector plugin

### PR DESCRIPTION
**Pull request by DispatchCommit**
Restores the quality selector to the site.

Uses a modified version of videojs-hls-quality-selector that detects source changes on the player and selectively hides or shows the quality selector dependent on if the file is an MP4 or M3U8 (HLS) file.

This is done by modifying the constructor for the plugin so that it is always active, and reactively hides or shows the control bar button based on data received from the loadedmetadata event which allows up to detect if a video is transcoded and has quality options or not.

This prevents us from having to re-create the entire video.js player when switching videos, and thus improves page speed slightly, and prevents creating extra garbage from repeatedly disposing the player.

### CODE REVIEW

**Comment by DispatchCommit** [comment]
resolves #5456

**Comment by DispatchCommit** [comment]
plugin forked from: https://github.com/chrisboustead/videojs-hls-quality-selector

**Comment by seanyesmunt** [comment]
Closing in favor of https://github.com/lbryio/lbry-desktop/pull/5548

**Comment by infinite-persistence** [comment]
Hi guys,  
Some minor (probably useless) observations:
1. When switching to another video _and_ if when `dispose` isn't invoke, there is an error message:
image
Not sure if it causes anything bad though, although I still don't see the button on the eevblog channel (used to see it there)
2. While the video is loading/buffering (mine takes a long time due to my region), the `AUTO` button is visible.  Not a big deal though, since the list, when clicked, is empty anyway.
image

**Pull request closed without merging**
