### PR TITLE
Added provision for adding multiple tags by using commas

### PR DESCRIPTION
**Pull request by pranabs1ngh**
## PR Checklist

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [x] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

Issue Number: 2833

## What is the current behavior?
There is no option for adding multiple tags at once

## What is the new behavior?
Added option for adding multiple tags using comma separated

### CODE REVIEW

**Comment by pranabs1ngh** [comment]
static/app-strings.json

This file wasn't changed by me. _Lines 736 to 743 got added out of nowhere._

**Comment by tzarebczan** [comment]
@pranabs1ngh, thanks for the PR! 

Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the contribution? 

Also, we're giving away some [Hacktoberfest](https://lbry.com/news/hacktoberfest-2019) bonuses and goodies for this month. We'll get it all figured out after you shoot us an email after this is reviewed/merged.

**Comment by tzarebczan** [comment]
See the appreciation faq linked above: lbry.com/faq/appreciation

Did you send us an email? I see one from you.

**Comment by pranabs1ngh** [comment]
Yes, I found the link in appreciation page and sent the mail. Just wanted to be sure. 

Thank You!!

**Pull request merged**
