### PR TITLE
[WIP] feat: disable app updates by placing a file named upgradeDisabled in static

### PR DESCRIPTION
**Pull request by jessopb**

### CODE REVIEW

**Comment by jessopb** [comment]
After initial review, we can ask @JoshStrobl to verify it accomplishes what he needs it to.

**Comment by kauffj** [comment]
I thought when we discussed this the answer was to have `doCheckUpgradeAvailable` simply never detect upgrades when the flag/file was set. Did that approach not work out?

**Comment by jessopb** [comment]
Settings page had a "Your app is up to date". I suppose if that's fine being untrue sometimes, we don't need the app state value.

**Comment by jessopb** [comment]
#3206

**Comment by JoshStrobl** [comment]
@kauffj Can confirm that shipping this file would be a perfect solution for disabling update checking, I can easily add supplementary files during packaging :+1:

**Comment by kauffj** [comment]
Great! @JoshStrobl when you see this merged you should be able to modify your build/release process accordingly.

**Comment by seanyesmunt** [comment]
Closing in favor of #3206

**Pull request closed without merging**
