### PR TITLE
Better Invite Page

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes
The invite page now displays 5 of the creators trending/top/new videos. Image below.
Screenshot from 2020-04-22 17-38-17

Issue Number: #4005

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Please let me know if I have to change some code according to some convention or style or if there is scope for any improvement whatsoever.

**Comment by seanyesmunt** [comment]
This looks great @HarshKhandeparkar !

**Comment by seanyesmunt** [comment]
Can you add a changelog entry?
https://github.com/lbryio/lbry-desktop/blob/master/CHANGELOG.md

**Comment by HarshKhandeparkar** [comment]
Yeah sure. I'll be back in a min.

**Comment by HarshKhandeparkar** [comment]
Do I need to worry about the travis failure?

**Comment by tzarebczan** [comment]
This is great @HarshKhandeparkar ! Once we get it merged/reviewed, can we show [you some appreciation](https://lbry.com/faq/appreciaiton)? 

IMO, the Create/Skip account could go near the top, maybe next to the channel or totally above it ? 
Seems strange at the bottom, especially if we want to drive new accounts.

**Comment by HarshKhandeparkar** [comment]
I think the skip is dynamically loaded. I think, if I were logged, it will be a `Done` button. What should I do, should I split the two?

**Comment by HarshKhandeparkar** [comment]
Ah yes, I found a bug while working on this. Apparently the infinite scroll does not work on smaller `pageSize` values i.e the number of video previews shown.

Should I open an issue for it?

**Comment by HarshKhandeparkar** [comment]
I think I will keep the skip button wherever it is and move the create button. Is that fine @tzarebczan?

**Comment by HarshKhandeparkar** [comment]
**Update**: Changed the location of the create account button as suggested by @tzarebczan.

Not signed in:
Screenshot from 2020-04-22 22-08-23

Signed in:
Screenshot from 2020-04-22 22-15-58

**Comment by HarshKhandeparkar** [comment]
**Update**: Added a CHANGELOG entry as requested by @seanyesmunt.

**Comment by seanyesmunt** [comment]
Whoops. I left a comment but never clicked "comment".

I think we can keep the buttons at the bottom since that's how they are on all cards. Can you drop the page size value to 3 though? Then it's shorter and the ad won't be displayed. Then I'll merge this.

 
I don't think you need to open an issue for what you described. When a custom page size is passed in, it is assumed that infinite scroll won't work.

**Comment by HarshKhandeparkar** [comment]
I changed the button to a link now, should I still revert the changes? I feel like it is more intuitive now.

**Comment by seanyesmunt** [comment]
I like the link. Lets keep the "create account" button at the bottom too.

**Comment by HarshKhandeparkar** [comment]
So both at top and bottom?

**Comment by HarshKhandeparkar** [comment]
Done.

**Comment by HarshKhandeparkar** [comment]
> Once we get it merged/reviewed, can we show you some appreciation?

You already showed me (a lot of) appreciation. Besides, I don't really want any appreciation, I am here to make OpenSource great and to increase my own knowledge and gain experience. Hence, I donated my appreciation LBCs.

Thank you!

**Comment by kauffj** [comment]
That's very generous @HarshKhandeparkar! You're contributions are valuable and we're glad that you can learn from the experience as well.

**Pull request merged**
