### PR TITLE
Netapau labo

### PR DESCRIPTION
**Pull request by netapau**
## PR Checklist

Please check all that apply to this PR using "x":

- [ x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #3752

## What is the current behavior?
Tokens with spaces generate a display bug  
## What is the new behavior?
The display bug seems to be fixed  
## Other information
About
App | 0.44.0-rc.1
Daemon (lbrynet) | 0.65.0

### CODE REVIEW

**Comment by tzarebczan** [comment]
hey @netapau , congrats on the first PR to LBRY-Desktop - thank you! We'll get this reviewed soon.

Can we show you some [appreciation](https://lbry.com/faq/appreciation)?

**Comment by tzarebczan** [comment]
This is what I see in transifex, so they are coming over as such for all the languages. 

image

**Comment by netapau** [comment]
I see that I did not anticipate pluralization. 
So the solution will not be complete. I can try to continue if I'm going in the right direction but first I'm going to look better on Transifex

**Comment by netapau** [comment]
> This is what I see in transifex, so they are coming over as such for all the languages.
> 
> image

Transifex

The  issue is in Transifex, if there is a badly placed space. 
wget-strings

After one wget on fr.json file, you can see the space here.

**Comment by kauffj** [comment]
@netapau sorry for sitting on this. I felt bad merging it because it's papering over something broken with code. I'd really like to understand what's causing this in the first place. Would you have any interest in helping to investigate?

**Pull request closed without merging**
