### PR TITLE
Clear upgrade subscribed interval after declining

### LINKED ISSUE #1747: "Upgrade on Close" doesn't close because multiple modals open
## The Issue
If a user has the LBRY app open and an update is out, it will create a modal every 10 minutes. So if you try to click the "Upgrade on Close" button - it won't actually close because you need to click it multiple times.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### PR DESCRIPTION
**Pull request by doniyor2109**
Closes #1747

### CODE REVIEW

**Comment by tzarebczan** [comment]
@doniyor2109 thanks for for this PR, please see https://lbry.io/faq/tips if you are interested in a tip for your contribution! 

Just looking at this by inspection, it may prevent new upgrade modals from popping up if the user clicked decline, but I don't think it prevents multiple upgrade modals from stacking on each other if a user has the app running in the background and an update occurs.

**Comment by doniyor2109** [comment]
@tzarebczan How can I create new action for app actions?

**Comment by tzarebczan** [comment]
@doniyor2109 i just submitted a commit which should fix this issue, but haven't tested it yet. I'll let @seanyesmunt review first.

**Comment by doniyor2109** [comment]
@tzarebczan Ok

**Comment by doniyor2109** [comment]
@tzarebczan  Can you merge lbryio/lbry-redux/#66 and upgrade `lbry-redux`?

**Comment by seanyesmunt** [comment]
@doniyor2109 Looks good. I merged the lbry-redux PR and bumped the version in this PR. I'll give it a better test tomorrow before merging. Thanks for the contribution!

**Comment by tzarebczan** [comment]
Thanks again @doniyor2109, was able to test and it worked!

**Comment by doniyor2109** [comment]
@tzarebczan I am glad to help 👌

**Pull request merged**
