### PR TITLE
Show on content page if a file is part of a playlist already

### LINKED ISSUE #6206: Content page should reflect if a file is part of a playlist already
YouTube doesn't have this one either. Maybe turn the Save option to a different color + show playlists on mouse over? Can't tell if it's in a playlist from here unless you click the option.

### PR DESCRIPTION
**Pull request by saltrafael**
## PR Checklist

Please check all that apply to this PR using "x":

- [X] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: Closes #6206

[](https://postimg.cc/6TcsRvs2) [](https://postimg.cc/w17d9TGt)

Just indicates that the file is currently already saved in a List, the button is still the same and clicking allows to remove/edit

## Other information

[Requires lbryio/lbry-redux/pull/419]

### CODE REVIEW

**Comment by tzarebczan** [comment]
Thanks for the PR, this is a cool feature not even YT has! We'll get a review on it soon.

**Review by jessopb — CHANGES_REQUESTED** [review]
There's one comment on the redux side PR.

**Comment by jessopb** [comment]
Ok, testing this out. 
I merged the redux pr, so this one will need a redux bump / yarn.

**Comment by jessopb** [comment]
image
Something going on here with icon color.

**Comment by jessopb** [comment]
60bd918d5ee95ea4e597d1e5c6bccf992ef83d28 is the new redux hash. rebump?

**Pull request merged**
