### PR TITLE
Add Confirmation when sending Tip/Support

### LINKED ISSUE #2714: Confirmation when sending Tip/Support
Feedback from community member: Similar to the double confirmation we do on the wallet send page, something similar should happen for tips/supports (supports are less of an issue since they can be redeemed). This may have to be done inline on the existing modal since tips are already one.

### PR DESCRIPTION
**Pull request by jeffslofish**
Closes #2714

## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #2714

## What is the current behavior?
When tipping or adding support, the tip/support happens immediately when you click the send button.

## What is the new behavior?
When tipping or adding support a confirmation modal appears after clicking send. Clicking send on the confirmation modal will perform the tip/support.

### CODE REVIEW

**Comment by kauffj** [comment]
I'd like to propose two changes to this:

1. Do not double confirm on supports. These are easy and cheap to undo.
2. Expand the Purchase Confirmation setting in Settings to Purchase and Tip Confirmation. Respect this setting on whether to ask for a confirmation.

**Comment by jeffslofish** [comment]
I found #4057 while making the second change requested above. I can't complete that task until #4057 is addressed.

**Comment by seanyesmunt** [comment]
@jeffslofish Just merged #4071 !

**Comment by tzarebczan** [comment]
Thanks again for the PR @jeffslofish ! Once you finish up, make sure to [reach out to us](https://lbry.com/faq/appreciaiton)!

**Comment by jeffslofish** [comment]
The requested changes were completed on April 23. See the commits here: https://github.com/lbryio/lbry-desktop/pull/4051/commits

**Pull request merged**
