### PR TITLE
Fix Transaction menu colides [#2000]

### PR DESCRIPTION
**Pull request by ykris45**
i tested on my local development 
image
if the position unchecked on my inspect element i will looks like
image
as @seanyesmunt said on issues #2000 ..

### CODE REVIEW

**Comment by seanyesmunt** [comment]
@ykris45 I belive this messes with the invite table. Isn't that why you removed it originally?

**Comment by ykris45** [comment]
@seanyesmunt on invite table it use same element with transaction table, i added position: relative; to tis element.

**Comment by seanyesmunt** [comment]
Based on #1985 

This will break the invite table. I think a better fix is described in #2000

**Comment by ykris45** [comment]
@seanyesmunt 
image i think it wouldnt break the invite table

**Comment by ykris45** [comment]
https://css-tricks.com/absolute-relative-fixed-positioining-how-do-they-differ/

**Comment by ykris45** [comment]
image
@seanyesmunt it will show based on my screenshot

**Comment by ykris45** [comment]
@seanyesmunt thanks brow

**Pull request merged**
