### PR TITLE
Documentation: Important changes in Readme.md

### PR DESCRIPTION
**Pull request by prateekpardeshi**
Documentation: Added Logo at Center, Text-Center Alignment,URL addition in Readme.md

## PR Checklist

Please check all that apply to this PR using "x":

- [ ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [x] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [x] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number:

## What is the current behavior?

Just Simple Text was Written

## What is the new behavior?

Added new Formatting in the documentation, added logo at the center, as well as center alignment of text including the addition of new 33 lines of code

### CODE REVIEW

**Comment by tzarebczan** [comment]
Like really really important?

**Comment by prateekpardeshi** [comment]
@seanyesmunt Please review the new changes and merge my PR! #3079

**Comment by prateekpardeshi** [comment]
@tzarebczan Makes Readme attractive and readable

**Comment by prateekpardeshi** [comment]
@seanyesmunt Review the changes in Readme and merge my PR. #3079 

Updated Readme.md looks like :
lbry

**Comment by tzarebczan** [comment]
@prateekpardeshi, thanks for the PR! Congrats on the first one here :)

Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the contribution? 

Also, we're giving away some [Hacktoberfest](https://lbry.com/news/hacktoberfest-2019) bonuses and goodies for this month. We'll send you the information when you reach out to us.

**Pull request merged**
