### PR TITLE
Report infringing content within app

### PR DESCRIPTION
**Pull request by miikkatu**
This is a suggested implementation for #909.

This is work-in-progress, as there is a CORS issue when posting the report, as discussed with @maximest-pierre.

### CODE REVIEW

**Comment by seanyesmunt** [comment]
This is looking good, a couple comments.

Most of this should live in redux. We should be doing api calls in action creators to keep components simple. You should also avoid mixing props and internal state like you are doing in this line:
`identifier: this.props.params.uri !== undefined ? this.props.params.uri : '',`

I propse creating a `report` reducer. Which will handle fetch errors, and loading while the api call is being made. The form values don't need to be stored in it, so `Formik` would be a good solution for this, similar to how we do it with the shapeshift component.

**Comment by miikkatu** [comment]
> I propose creating a report reducer. Which will handle fetch errors, and loading while the api call is being made. The form values don't need to be stored in it, so Formik would be a good solution for this, similar to how we do it with the shapeshift component.

Looks like this would require more time than I currently have, unfortunately. Hopefully someone else can continue from here.

**Comment by alyssaoc** [comment]
closing, looking at a new direction/solution

**Comment by seanyesmunt** [comment]
@miikkatu We may come back to this. I will re-open if we decide to go with this solution.

**Pull request closed without merging**
