### PR TITLE
Better Hover, Subscribe Button

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes
- The hover `useEffect` hook in `/ui/effects` is now more reliable.
- The subscribe button is optimized for both desktop and mobile.
- Doesn't completely fix but improves the situation of the de-sync issue.
- Removed some redundant code and cleaned the subscribe button component.
```js
  if (__('Following').length < __('Unfollow').length) {
    longestStr = __('Unfollow');
  }
```
Issue Number: #4048 

## What is the current behavior?
- The title of the subscribe button may get out of sync if used too fast.
- It cannot recover from the de-sync.
- Hover events are fired on mobile devices too and they may affect the UX.

## What is the new behavior?
- It is much more difficult for the subscribe button to get out of sync.
- Even if it gets out of sync, it can recover leading to a much better UX.
- Mobile hover events cannot be stopped because of the way react hooks work but the events do not affect the state anymore.

#### Desktop Hover
better-hover-desktop

#### Mobile Hover
better-hover-mobile

#### Simulated De-Sync (to demonstrate the recovery)
simulated-hover-desync

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@seanyesmunt ?

**Comment by seanyesmunt** [comment]
Nice. Works great!

**Comment by seanyesmunt** [comment]
@HarshKhandeparkar Can you add a changelog entry?
https://github.com/lbryio/lbry-desktop/blob/master/CHANGELOG.md

**Comment by HarshKhandeparkar** [comment]
**Update**: Added a changelog entry.

**Comment by HarshKhandeparkar** [comment]
Thank you!

**Pull request merged**
