### PR TITLE
In-app text and markdown publishing

### PR DESCRIPTION
**Pull request by btzr-io**
> ### ⚠️  Experimental branch

## PR Checklist

Please check all that apply to this PR using "x":

- [ ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number:

### CODE REVIEW

**Comment by btzr-io** [comment]
First UI draft, just the basic component structure ( missing main logic )

test_UI

**Comment by btzr-io** [comment]
Waiting for: 
> add file text to publish state [#330](https://github.com/lbryio/lbry-redux/pull/330)

**Comment by kauffj** [comment]
I WAS ON VACATION SO I AM LATE TO EXPRESS MY EXCITEMENT

HOPEFULLY ALL CAPITAL LETTERS MAKES UP FOR IT

**Comment by seanyesmunt** [comment]
@btzr-io I merged your lbry-redux pr. You can point the desktop at 85f0f574bd082ca5d0b87dcba11863fb3f050555

**Comment by kauffj** [comment]
@btzr-io are you unblocked on this?

**Comment by btzr-io** [comment]
@kauffj yeah, I'm still experimenting on some things, cant push changes yet

**Comment by btzr-io** [comment]
Almost there, somethings left to do:
- [ ] Smooth transition between file and story mode 
- [ ] Make it work on the web
- [ ] Test: claim edit
- [ ] Test: claim publish

**Comment by btzr-io** [comment]
Looks like my machine don't have any register of the `markdown` content type

**Comment by btzr-io** [comment]
Now publishing a "story" should  also work on web, I'm still not sure how to handle the editing part.
How can I get the file contents on the web version file ( lbry.tv )? should I just use the streaming url ( also how can I get it ) ?

**Comment by seanyesmunt** [comment]
I'm not sure of a better way to do that, but since this is only for markdown files, I think just checking the content type should be ok.

I think you will need to use the streaming url web, to get the streaming URL, you need to call `Lbry.get`, then can access it with `makeSelectStreamingUrlForUri`. Can you just delete the old file after creating a new one? 

> Also If the user removes the file from desktop, will this be handled in a similar way ?

I'm not sure what that means. Aren't these just temporary files? I didn't think the user would see them.

**Comment by seanyesmunt** [comment]
@btzr-io How is this going? Anything I can help with?

**Comment by btzr-io** [comment]
@seanyesmunt Almost done, a few flow warnings / errors I need to fix, I'll let you know if I have more questions

**Comment by btzr-io** [comment]
****

**Comment by btzr-io** [comment]
I'll reopen a new one 😛

**Pull request closed without merging**
