### PR TITLE
Added More Languages on Publish Form

### PR DESCRIPTION
**Pull request by ykris45**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Referenced Issues

https://github.com/lbryio/lbry-desktop/issues/2455 as @tzarebczan said on below.. 

I added 14 Languages for now

### CODE REVIEW

**Comment by tzarebczan** [comment]
These need to come from our protobuf values dynamically. We could probably do this round manually, but please reference the issue to make sure those values are available .

https://github.com/lbryio/lbry-desktop/issues/2455

**Comment by ykris45** [comment]
okay,, just help user named Link on our chat room sir

**Comment by seanyesmunt** [comment]
@tzarebczan if the values added here are correct, i think we should include this before #2455, just to get some more languages in

**Comment by ykris45** [comment]
this value are correct based on iso code of these countries

**Comment by tzarebczan** [comment]
Thanks for checking @ykris45 ! LGTM @seanyesmunt

**Comment by ykris45** [comment]
Thanks You Mr Thomas..

**Comment by seanyesmunt** [comment]
Had issues with merging this branch so I just created a new commit and pushed to master. Will be included in the next release @ykris45 !

**Pull request closed without merging**
