### PR TITLE
Fix: Added \ and = to Reserved symbols warning

### PR DESCRIPTION
**Pull request by Eniamza**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I added a line describing my change to CHANGELOG.md
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number:

## What is the current behavior?

Currently, the warning lacks 2 symbols which are considered as reserved symbols when entering

## What is the new behavior?

The warning is updated with new symbols

### CODE REVIEW

**Comment by tzarebczan** [comment]
Thanks @Eniamza . Did you test this locally to see if an additional \ is needed to escape the \ ?

**Comment by Eniamza** [comment]
Yup @tzarebczan, One \ was being considered as an escape for =, two \ are cancelling out the escape for both \ and =

image

**Comment by tzarebczan** [comment]
Thx for confirming!

**Comment by tzarebczan** [comment]
I fixed the rebase issue and it pushed to master directly, whoops: https://github.com/lbryio/lbry-desktop/commit/c146bfcd2d7c3cbbc8953f58efb309fa0524b466

**Pull request closed without merging**
