### PR TITLE
Combine Buy and Swap

### LINKED ISSUE #5873: Unify swap and buy flow // swaps round #2
- Combine buy/swap into one flow
- Audit drivers to buy flow to incorporate above
- Swap history merged into transaction history (if not difficult)

### PR DESCRIPTION
**Pull request by infinite-persistence**
## Issue
Fixes #5873 Unify swap and buy flow // swaps round 2

## Changes
- Removed 'Swap' button from Wallet Page.
- <strike>'Buy' button in wallet page now goes into an intermediate page for users to choose between "Buy" or "Swap".
  - This is a new Option 1.5 (deviated from [Option 1](https://lbryians.slack.com/archives/CBNPKBU8G/p1620998526324000?thread_ts=1620157429.296300&cid=CBNPKBU8G)). The amount of refactoring to do Option 1 doesn't seem worth it (at that point, might as well attempt Option 2), plus I couldn't find a way to get the estimated USD without the Moonpay iframe.</strike>
  - _Update_: Simplified to just adding a tab in the Buy Page
- <strike>Point all "Buy More" buttons to the new intermediate page</strike>. Tooltip is updated to "Buy or Swap Credits" as well.

## Notes
<strike>The paragraph on the left-hand side seems redundant.  Could be improved.</strike>

## Screenshot
<strike>image</strike>

### CODE REVIEW

**Comment by kauffj** [comment]
Please drop this screen:

Screenshot from 2021-05-25 11-19-21

Instead, buy or swap should go directly to a page like this, with tabs that let you switch between:

instead

**Review by kauffj — CHANGES_REQUESTED** [review]
Changes requested, comments shared directly on the PR

**Comment by infinite-persistence** [comment]
`Update`
- Simplified to just adding tabs to Buy Page + text renaming

**Review by kauffj — APPROVED** [review]
LGTM

**Pull request merged**
