### PR TITLE
Clear publish form when publishing from header

### PR DESCRIPTION
**Pull request by Ruk33**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: https://github.com/lbryio/lbry-desktop/issues/5366

## What is the current behavior?

- User edits a claim
- Doesn't finish and leaves the section
- Clicks on Publish
- The form isn't clean and remains with the previous edited claim 

## What is the new behavior?

The publish form now gets cleared when creating a new claim.

## Other information

NOTE: This PR depends on https://github.com/lbryio/lbry-redux/pull/385

### CODE REVIEW

**Comment by seanyesmunt** [comment]
@Ruk33 I don't think this is the correct fix. We still want to allow starting a publish, then coming back to it later to finish it.

**Comment by Ruk33** [comment]
Hello @seanyesmunt , thanks for the reply. Could you elaborate on the requirements? I'm facing a lot of possible scenarios that could be solved differently and I don't know how far we want to go. Thanks!

**Comment by seanyesmunt** [comment]
@Ruk33 The first step would be to reproduce the bug from the original issue (maybe it is already resolved). When you have a successful publish, all of the publish fields should be cleared out.

**Comment by seanyesmunt** [comment]
@Ruk33 I'm going to close this since it isn't quite what is needed. Feel free to re-open if you figure out what is going wrong with that bug.

**Pull request closed without merging**
