### PR TITLE
Add reward code redemption

### PR DESCRIPTION
**Pull request by seanyesmunt**
https://github.com/lbryio/lbryinc/pull/7 Needs to be merged first

Also adds support for `lbryinc` hot reloading the same way we do it for `lbry-redux`

### Changes
screen shot 2018-09-25 at 8 11 15 pm

screen shot 2018-09-25 at 8 11 25 pm

### CODE REVIEW

**Comment by seanyesmunt** [comment]
This is currently blocked until we decide on a solution for using `lbryinc` in the desktop repo. Reward changes needed for this PR should be added there.

**Comment by seanyesmunt** [comment]
@tzarebczan Will there be a faq for this?

**Comment by seanyesmunt** [comment]
I will also go through and make sure modal styles are consistent in this PR for https://github.com/lbryio/lbry-desktop/issues/940. Those will be very basic changes.

**Comment by seanyesmunt** [comment]
@skhameneh Touched every single modal file, but it's just moving markup around.

**Comment by tzarebczan** [comment]
@seanyesmunt I don't think we'll need a FAQ, just need to be clear enough in the messaging. Maybe something along the lines of 
"Did you receive or find a LBRY reward code?" Redeem it today for LBC! 

Maybe @robvsmith / @kauffj could provide some feedback on the messaging.

**Comment by kauffj** [comment]
@seanyesmunt

- Reward Header: "Custom Code"
- Reward Description: "Are you a supermodel or rockstar that received a custom reward code? Claim it here."
- Modal subtext: "Read a custom reward code for LBC. Learn more."

**Comment by tzarebczan** [comment]
Added this to the rewards FAQ instead of creating a new one: https://lbry.io/faq/rewards#reward-code

**Pull request merged**
