### PR TITLE
refactors and enhances tip modal

### PR DESCRIPTION
**Pull request by jessopb**
Tip modal now disables send button on all invalid actions and shows feedback.
tip_
tipequalsbalance
tipgreaterthanbalance
tipmanydots
tipmaxdecimal
tippointfive
tiptoomanydecimals
tiptwenty

### CODE REVIEW

**Comment by jessopb** [comment]
Oh, I remember noticing that before. Modification on line 85.

**Comment by kauffj** [comment]
Not strictly necessary, but splitting the "tip must be a valid number with no more than 8 decimals places" into more messages would improve UX:

- "Tip must be a number" (shown if anything other than a number is entered - can also drop valid, it conveys no additional information)
- "Tip must be positive" (I've now deduced what was meant by the word valid)
- "Tip must not be more than 8 decimal places" (shown if a 9+ decimal number is entered)

**Comment by jessopb** [comment]
I hear you. I'm glad to get specific input on the actual messages.
 I'll have something shortly.

**Comment by jessopb** [comment]
I'm noticing this functionality duplicated in 3 places: Publish>deposit, page>file>...>walletSendTip, and Wallet>walletSend. All three are basically the same FormField that informs a button to be disabled. The form field could stand to be wider as well, I think. Thoughts? Make it component?

**Comment by seanyesmunt** [comment]
I think making the input/label into it's own component sounds like a great idea!

**Comment by tzarebczan** [comment]
@jessopb any updates here? Will the last comments also occur in this PR or a separate one?

**Comment by jessopb** [comment]
The latest commit does precisely what @kauffj suggests.

**Pull request merged**
