### PR TITLE
Chromecast integration (experimental)

### PR DESCRIPTION
**Pull request by mikadoplus**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: https://github.com/lbryio/lbry-desktop/issues/508

### CODE REVIEW

**Comment by seanyesmunt** [comment]
Awesome! I'll review/test this later today or tomorrow.

**Comment by seanyesmunt** [comment]
This looks like a great start! I'm ok using your changes in your fork if they are absolutely needed.

If we do, I would rather you publish that to NPM.

Can you also make sure this doesn't cause the web build to fail? When I run `yarn dev:web` if fails with a couple errors.

**Comment by seanyesmunt** [comment]
I'm seeing this when I try to cast to my TV. It also doesn't actually stop the video that is playing when I click the "cast" button.

Screen Shot 2020-05-28 at 1 32 54 PM

**Comment by mikadoplus** [comment]
Hello @seanyesmunt, no big deal for the errors on yarn dev:web, I saw them, and should work, indeed they already work on my side, but somehow the packages weren't up to date when I created the PR.
For the other error, that is what I said on my first comment. The problem here is that videos are played on a localhost URL with a specific port. So I assume Chromecast doesn't see it since it is playing on your mac or pc. I've tried with the web version "CDN Urls" and they worked. The main video stops and it's casted.

I'll investigate on this a bit further by tonight or tomorrow.

I think also that the error handling could be more intuitive for the user.

I see also on your screen some weird design glitches, I do not have, will investigate on that to.

**Comment by seanyesmunt** [comment]
@mikadoplus Ah that makes sense. I'll try not on localhost!

**Comment by mikadoplus** [comment]
Hi @seanyesmunt I've update the my last commit, the errors executing warn dev:web. Are now corrected. I've also improved the performance and user experience a bit. Let me know what do you think about this one.

Were you able to play non localhost videos ?

**Comment by seanyesmunt** [comment]
I haven't tested that yet. Will do today. Can you rebase this PR so it doesn't include all of the extra commits?

**Comment by mikadoplus** [comment]
Hi @seanyesmunt I just noticed I messed up this PR, didn't notice I've forced a push out here. Sorry about that. I should have created a new branch instead of continue commiting to the master one. I've pushed a new commit, but don't want to recreate a new PR if there is an other way to roll back this one. Maybe I'm not enough familiar with git but what would be the best way to do it ?

**Pull request closed without merging**
