### PR TITLE
Add loading animation to search page

### PR DESCRIPTION
**Pull request by nestordominguez**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number:

### CODE REVIEW

**Comment by nestordominguez** [comment]
This is my first pr in my whole life to a project open source, I'm happy :)

**Comment by seanyesmunt** [comment]
So cool! I'll check this out tomorrow!

Thanks for the PR! 🙂

**Comment by seanyesmunt** [comment]
Looks great! Can we show you some appreciation for this contribution?
https://lbry.com/faq/appreciation

**Comment by nestordominguez** [comment]
Thank you, I followed your instructions and I sent a email

**Comment by nestordominguez** [comment]
fixes https://github.com/lbryio/lbry-desktop/issues/2171

**Pull request merged**
