### PR TITLE
Improve sidenav subscriptions appearance

### PR DESCRIPTION
**Pull request by saltrafael**
## PR Checklist

Please check all that apply to this PR using "x":

- [ ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number:

## What is the current behavior?

Currently the sidenav shows subscriptions only as their handle (@ lbry, @ odysee)

## What is the new behavior?

Changed it to show the channel thumbnail and title instead, to look better

### CODE REVIEW

**Review by seanyesmunt — CHANGES_REQUESTED** [review]
Thank you for the PR! This feature would actually require an additional change so that we resolve all of a users channels together, instead of doing it separately for every channel which is what happens in this PR. 

You will need to call `doResolveUris(subscriptionUris)` so that they are all resolved together

**Comment by kauffj** [comment]
@saltrafael cool! Thanks for this contribution, hope to see more from you :)

**Comment by saltrafael** [comment]
@seanyesmunt thanks for the update! is this any better?

@kauffj thank you! Hoping to contribute more

**Comment by kauffj** [comment]
@seanyesmunt is on vacation for about a week, asking @DispatchCommit to take a look

**Comment by saltrafael** [comment]
@kauffj no problem, my channel is https://odysee.com/@RafaelS:2 thank you!

**Comment by seanyesmunt** [comment]
Thanks for this PR. I am going to close it for now until we can better plan out how this should work for people with very large subscription lists. Right now this will cause some startup slowdown if you are following a lot of channels.

**Pull request closed without merging**
