### PR TITLE
Add channel subscriptions count below author.

### PR DESCRIPTION
**Pull request by Ruk33**
## Fixes

Issue Number: https://github.com/lbryio/lbry-desktop/issues/6746

## What is the current behavior?

N/A

## What is the new behavior?

Display channel subscription below authors.

image

## PR Type & Checklist

<details><summary>PR Type...</summary>

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

</details>

<details><summary>PR Checklist...</summary>

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I added a line describing my change to CHANGELOG.md
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

</details>

### CODE REVIEW

**Comment by tzarebczan** [comment]
Thank for the PR! We'll want this to say Followers to match the channel page. 

We'll get a review on it soon otherwise!

**Comment by Ruk33** [comment]
Sure @tzarebczan , updated!

**Comment by tzarebczan** [comment]
DId some more testing on this and noticed the API for sub count is being called multiple times- both on refresh and when coming from another page (i.e. related content click). In the latter case, saw it called 3x. @Ruk33 probably not the end of the world, but maybe you can take a look.

**Comment by Ruk33** [comment]
Thank you @tzarebczan you were right. I managed to fix it and merge the conflicts.

**Comment by tzarebczan** [comment]
Great, thanks again!

**Pull request merged**
