### PR TITLE
[WIP] Include tip with comment

### PR DESCRIPTION
**Pull request by osilkin98**
Includes an option to add a tip to a comment before posting 
Also removes 'Comments' section title to make the design look neater

- converse ability in the tipping 
- tips are coupled with comments

### CODE REVIEW

**Comment by tzarebczan** [comment]
Planning to add some indication to the comment that it included a tip?

**Comment by kauffj** [comment]
Let :ship:

**Comment by seanyesmunt** [comment]
@osilkin98 is this ready for review? Or does it require more work?

**Comment by osilkin98** [comment]
This needs SDK-side work to support the desired functionality.

**Comment by seanyesmunt** [comment]
Why can’t we just send a tip after commenting? The functionality can be separated even if it’s bundled in the ui

**Comment by osilkin98** [comment]
Jeremy wanted them to be coupled, though I would be perfectly fine with
that solution for the time being.

**Comment by seanyesmunt** [comment]
is that something you plan to work on soon sdk side?

**Comment by osilkin98** [comment]
Yes

**Comment by kauffj** [comment]
There may have been some confusion in what I meant by coupling. It needs to be presented to user as a unitary function and _ideally_ both tip and comment would happen atomically.

However, I think it would be okay to send the tip, let that succeed, and then submit the comment.

**Pull request closed without merging**
