### PR TITLE
Improve twitter share

### PR DESCRIPTION
**Pull request by btzr-io**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I added a line describing my change to CHANGELOG.md
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number:  #6678
Changelog update: #6735

### CODE REVIEW

**Comment by kauffj** [comment]
Please make the Twitter share handle an environment variable, rather than `IS_ODYSEE` flag.

**Review by kauffj — CHANGES_REQUESTED** [review]
Please make Twitter handle an environment variable

**Review by jessopb — APPROVED** [review]

**Comment by jessopb** [comment]
This is good - can you catch up with CHANGELOG.md going forward?

**Comment by btzr-io** [comment]
I'll open a new pull request to update the changelog with all my changes.

**Comment by btzr-io** [comment]
Changelog update: #6735

**Comment by jessopb** [comment]
.env updated on production

**Comment by kauffj** [comment]
LGTM, thanks for this adjustment!

**Review by kauffj — APPROVED** [review]

**Pull request merged**
