### PR TITLE
Upgrade to yarn v3

### PR DESCRIPTION
**Pull request by tiziodcaio**
## Fixes

Issue Number: #7529 

## What is the current behavior?

Using yarn classic

## What is the new behavior?

Using yarn v3

## Other information

yarn upgrade is now yarn up and maybe other features have been deprecated. I checked all the script used before upgrading

I don't thing it could be called a breaking change, but I prefer advice.

## PR Checklist

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

Please check all that apply to this PR using "x":

- [X] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I added a line describing my change to CHANGELOG.md
- [X] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

</details>

### CODE REVIEW

**Comment by jessopb** [comment]
```
➤ YN0002: │ lbry@workspace:. doesn't provide @types/react (pf358f), requested by react-hot-loader
➤ YN0002: │ lbry@workspace:. doesn't provide immutable (pa1bbe), requested by connected-react-router
➤ YN0060: │ lbry@workspace:. provides react (p4fdc7) with version 16.14.0, which doesn't satisfy what @mui/material and some of its descendants request
➤ YN0060: │ lbry@workspace:. provides react-dom (p773b6) with version 16.13.0, which doesn't satisfy what @mui/material and some of its descendants request
➤ YN0060: │ lbry@workspace:. provides redux (p476c7) with version 3.7.2, which doesn't satisfy what redux-thunk requests
➤ YN0002: │ lbry@workspace:. doesn't provide seamless-immutable (p9ca63), requested by connected-react-router
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code

```
`yarn` fails with errors. I guess we need to update peer dependencies?

**Comment by tiziodcaio** [comment]
These are warnings

The error I think it is

```
  ➤ YN0000: │ /tmp/xfs-7405dbd5 STDOUT Packing lbry-format@https://github.com/lbryio/lbry-format.git#commit=6208a7df71eca6cc5bd9bfb6685acad5865495f4 from sources
  ➤ YN0000: │ /tmp/xfs-7405dbd5 STDOUT Using npm for bootstrap. Reason: found npm's "package-lock.json" lockfile
  ➤ YN0000: │ /tmp/xfs-7405dbd5 STDOUT 
  ➤ YN0000: │ /tmp/xfs-7405dbd5 STDERR npm WARN lbry-format@0.1.0 No repository field.
  ➤ YN0000: │ /tmp/xfs-7405dbd5 STDERR 
  ➤ YN0000: │ /tmp/xfs-7405dbd5 STDOUT added 207 packages from 124 contributors and audited 207 packages in 41.537s
  ➤ YN0000: │ /tmp/xfs-7405dbd5 STDOUT found 20 vulnerabilities (10 moderate, 7 high, 3 critical)
  ➤ YN0000: │ /tmp/xfs-7405dbd5 STDOUT   run `npm audit fix` to fix them, or `npm audit` for details
  ➤ YN0000: │ /tmp/xfs-7405dbd5 STDOUT lbry-format-0.1.0.tgz
  ➤ YN0000: │ /tmp/xfs-454f256d STDOUT Packing lbry-format@https://github.com/lbryio/lbry-format.git#commit=6208a7df71eca6cc5bd9bfb6685acad5865495f4 from sources
  ➤ YN0000: │ /tmp/xfs-454f256d STDOUT Using npm for bootstrap. Reason: found npm's "package-lock.json" lockfile
  ➤ YN0000: │ /tmp/xfs-454f256d STDOUT 
  ➤ YN0000: │ /tmp/xfs-454f256d STDERR npm WARN lbry-format@0.1.0 No repository field.
  ➤ YN0000: │ /tmp/xfs-454f256d STDERR 
  ➤ YN0000: │ /tmp/xfs-454f256d STDOUT added 207 packages from 124 contributors and audited 207 packages in 30.426s
  ➤ YN0000: │ /tmp/xfs-454f256d STDOUT found 20 vulnerabilities (10 moderate, 7 high, 3 critical)
  ➤ YN0000: │ /tmp/xfs-454f256d STDOUT   run `npm audit fix` to fix them, or `npm audit` for details
  ➤ YN0000: │ /tmp/xfs-454f256d STDOUT lbry-format-0.1.0.tgz
  ➤ YN0018: │ lbry-format@https://github.com/lbryio/lbry-format.git#commit=6208a7df71eca6cc5bd9bfb6685acad5865495f4: The remote archive doesn't match the expected checksum
```

**Comment by jessopb** [comment]
can you just remove the lbry-format dependency? that stuff was disabled 2 years ago.

**Comment by tiziodcaio** [comment]
Sure... When I will be able to use a pc I will do it!

**Comment by jessopb** [comment]
Ready to merge this. Could you rebase and run yarn to update the yarn lock?

**Pull request closed without merging**
