### PR TITLE
Modal repost

### PR DESCRIPTION
**Pull request by bradley-ray**
## Fixes

Issue Number:  #7255

## What is the current behavior?
Currently when the repost button is clicked, a new page is opened in order to repost content. Also would redirect to new channel page if user did not have a channel made.
## What is the new behavior?
Now when repost is clicked a pop up appears with the repost information. If user does not have a channel, a notification appears informing them they need to create one along with a link to the /channel/new page.
## PR Checklist

<details><summary>Toggle...</summary>

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

Please check all that apply to this PR using "x":

- [X] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I added a line describing my change to CHANGELOG.md
- [X] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

</details>

### CODE REVIEW

**Comment by jessopb** [comment]
Thanks! I'll take a look soon.

**Comment by jessopb** [comment]
Looks pretty close! The direction makes sense
A few things - 
If you yarn lint, it'll show you a few things to fix. (unused vars, a semicolon, etc)
There are a few more places where PAGES.REPOST_NEW is used that should (probably?) use this component.
I know the modal internal spacing generally isn't great, but the channel selector is smushed to the top corner.
image
Maybe give it a Title section like this?
image

**Comment by bradley-ray** [comment]
Sounds good. I think given the context of the other PAGES.REPOST_NEW, having repost be a separate page in those instances rather than a modal makes more sense.

**Comment by jessopb** [comment]
Alright, that sounds ok.

**Comment by bradley-ray** [comment]
Should be good to go now I think.

**Pull request merged**
