### PR TITLE
Comments

### PR DESCRIPTION
**Pull request by seanyesmunt**

### CODE REVIEW

**Comment by kauffj** [comment]
@jessopb @NetOperatorWibby will do styling and presentation work for this. Please involve him once routing/redux portion is complete.

**Comment by kauffj** [comment]
@jessopb @netoperatorwibby check out https://storybook.js.org/ and see if it's worth trying for the work on this, @seanyesmunt says it could be useful (I haven't done a deep dive yet)

**Comment by kauffj** [comment]
This is blocked by SDK issues (not sure issue exists)

**Comment by jessopb** [comment]
closed - refer to #2510

**Pull request closed without merging**
