### PR TITLE
#2411

### PR DESCRIPTION
**Pull request by abueide**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #2411

## What is the current behavior?
Window icon doesn't show up on some linux desktop environments.
## What is the new behavior?
Window icon shows up on xfce4

### CODE REVIEW

**Comment by skhameneh** [comment]
@tzarebczan can you check the windows prod build with this change?
It might need `file://${__dirname}/` prefixed, not sure.

**Comment by skhameneh** [comment]
Thanks for the PR @abueide!

**Comment by tzarebczan** [comment]
Hey @abueide , congrats on the first PR!! Can we show you some [appreciation for your contribution?](https:/lbry.com/faq/appreciation)

I'll give this is a shot on Windows to make sure nothing broke.

**Comment by abueide** [comment]
@tzarebczan I was able to build this in my windows vm without any errors, and it even showed the lbry icon on the top left in windows as well.

**Comment by tzarebczan** [comment]
@abueide Thanks for running through this. I tested on Windows/Linux/Mac and it looks good. Not sure why you were seeing the electron icon before...that should only happen in Dev mode.

**Comment by abueide** [comment]
@tzarebczan oh I was running in dev mode

**Pull request merged**
