### PR TITLE
Validate thumbnails

### PR DESCRIPTION
**Pull request by daovist**
#1362 

Inform the user whether their manually entered thumbnail URL is valid and display a preview of it.

I mostly forgot how to do CSS after Bootstrap came out and most of my early website gigs were pixel-to-HTML so my design skills are severely lacking. This will probably need some input/touchup from others.

manual thumbnail preview

### CODE REVIEW

**Comment by kauffj** [comment]
Great idea! (Agreed UI should likely change a bit)

**Comment by seanyesmunt** [comment]
This is awesome. Will think about how we can display this in the app.

**Comment by seanyesmunt** [comment]
Current design:
screen shot 2018-07-18 at 11 56 20 am

screen shot 2018-07-18 at 11 55 51 am

screen shot 2018-07-18 at 11 53 45 am

**Comment by seanyesmunt** [comment]
I think the only thing left would be to create a proper "No thumbnail chosen" (or whatever we want to call it) image to use instead of the quick one I added.

**Pull request merged**
