### PR TITLE
Post and Description Enhancements

### PR DESCRIPTION
**Pull request by ElectronEsq**
These changes fill more of the whitespace with larger more spacious text, while keeping the character count the same or less. for better aesthetics and readability. Margins were increased between some elements that were touching other elements.

## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number:

## What is the current behavior?

Too narrow and too small. Not aesthetically pleasing and hard to read.
Elements missing margins making them touch other elements.

## What is the new behavior?

Larger, wider cleaner, more aesthetically pleasing.

## Other information

Before:
image

After:
image

### CODE REVIEW

**Comment by seanyesmunt** [comment]
Thanks for the PRs @ElectronEsq 

I'll check these out after the next app release is out

**Comment by ElectronEsq** [comment]
After all these years of using Github, I still don't know how to combine all those PRs in to one. I tried with a previous PR and it said I couldn't. Probably something really simple. If you can point me in the right direction, I'll merge all three in to one.

**Comment by seanyesmunt** [comment]
I'm not sure how you would combine them. But it's not a big deal.

**Comment by seanyesmunt** [comment]
Still waiting on an SDK release so I finally got to test this out. 

I don't plan to merge any changes to the font-{size,weight}/word-spacing. I can merge the blockquote margin changes if the other changes are removed. Sorry it took so long to review

**Comment by ElectronEsq** [comment]
> I'm not sure how you would combine them. But it's not a big deal.

The files needed to be in a group PR, because some of the changes relied on the other changes, one wouldn't work without the other. Maybe that should be a feature request for GitHub. I just thought there would be an option for that. An organised thing for people that suffer from OCD, haha!

**Pull request closed without merging**
