### PR TITLE
i18n: Added missing state handling for RTL languages

### PR DESCRIPTION
**Pull request by marko-lorentz**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #4430 

## What is the current behavior?

* RTL languages are not rendered correctly in RTL mode but in LTR.
* Arabic language is not offered in language switcher.

## What is the new behavior?

* Arabic language available in language switcher.
* Rendering of RTL languages should be fixed and will follow the choice of the current language for Arabic, Urdu and Farsi.

## Other information

Some translation updates in Transifex needed for Arabic. Will be done asap.

### CODE REVIEW

**Comment by tzarebczan** [comment]
Hey @marko-lorentz , thanks so much for the PR. Please give us a few days to take a look and review. 

Can we show you some [appreciation](https://lbry.com/faq/appreciation)?

**Comment by marko-lorentz** [comment]
Hi @tzarebczan, 
The work on issue #4430 (as well as most of the Arabic translations in Transifex) was mainly done by my working student @sanabhass as an exercise. I will ask her so send her data to the given email address for supporters. I think she will be happy when her work is honoured.

(Seems that we didn't run lint properly. I will try to have a look at this later.)

**Comment by jessopb** [comment]
This seems to work great - it looks like we have some issues with our translation service files such as 
`"Log in to %SITE_NAME% to earn rewards": "سجّل الدخول إلى٪ SITE_NAME٪ لتربح المكافآت",`
That break in some places.
We'll take a look at this and see what can be done in the next few days.

**Comment by marko-lorentz** [comment]
Did we break it in Transifex?

**Comment by jessopb** [comment]
I don't think it's your fault at all. Just have to look into it.

**Comment by marko-lorentz** [comment]
After some string inspection:
My student and me will need to fix some translations in Transifex because one of the translators not only included `SPACE` in the translation tokens but also used the Arabic percent sign `٪` instead of the latin one `%` so the pattern matching will not work properly.

**Comment by jessopb** [comment]
Ok, just tested, looks great. Sorry how time flies. One rebase and poke me?

**Comment by marko-lorentz** [comment]
Included latest changes from lbryio:master. Anything else I can do?

**Pull request merged**
