### PR TITLE
feat: add option to hide anonymous content

### PR DESCRIPTION
**Pull request by zxawry**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #2935 and probably #2890 

## What is the current behavior?
there is no option to block anonymous claims.

## What is the new behavior?
the option to hide anonymous claims is added to the settings page.

## Other information

this probably needs to improve, for example with the feature turned on, anonymous claims on library page are filtered too.

### CODE REVIEW

**Comment by tzarebczan** [comment]
@zxawry , we should also pass this param to claim search when the option is enabled: https://github.com/lbryio/lbry-desktop/issues/2935#issuecomment-536555236

This will make sure trending/top/new don't display it from the get go, as opposed to blocking it and potentially running into pagination issues.

**Comment by zxawry** [comment]
@tzarebczan I tried it but it filters channels as well, is it okay?

**Comment by tzarebczan** [comment]
@zxawry not sure I understand. If you pass something like this `lbrynet claim search --order_by=trending_global --has_channel_signature` it should return claims with channels, and filter out anonymous ones. Is that what you tried? 

So pretty much we'd wanna tack on `has_channel_signature: true` to the claim search for trending with the option is enabled.

**Comment by zxawry** [comment]
@tzarebczan, I mean channel claims e.g. `lbry://@history` that sometimes get listed in the discovery have no channel signature same as anonymous claims so they will be filtered too.

**Comment by tzarebczan** [comment]
Oh, I see. I think that's okay for now - we could just make a note of that in the copy. Once we add more filtering options as part of https://github.com/lbryio/lbry-desktop/issues/2801,we can ignore this option if someone uses the All/Channels selector for channels vs claims. 

@seanyesmunt do you agree?

**Comment by zxawry** [comment]
Is this considered appropriate to separate channel discovery from other claim types for the time being?
 
screenshot

**Comment by tzarebczan** [comment]
I think those options would be somewhere else under an advanced / filter menu. 

For now for this pr, I think your solution might be fine, and we'll introduce the parameter I was referencing later.   Unless @seanyesmunt disagrees.

**Comment by seanyesmunt** [comment]
I think the current solution is fine. I will update the copy for the setting help text then merge this.

**Comment by tzarebczan** [comment]
@zxawry, thanks for yet another awesome PR!

Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the contribution? 

Also, we're giving away some [Hacktoberfest](https://lbry.com/news/hacktoberfest-2019) bonuses and goodies for this month. We'll get it all figured out after you shoot us an email after this is reviewed/merged.

**Pull request merged**
