### PR TITLE
add togglable QR code to wallet address component

### PR DESCRIPTION
**Pull request by daovist**

### CODE REVIEW

**Comment by tzarebczan** [comment]
I'm not crazy about how the button looks on both light and dark themes. Maybe @seanyesmunt can work on styling it better. 

Also, doesn't work in dark mode - looks like some of the background is seeping through and adding some extra tiny lines to the QR. 
qr code

**Comment by seanyesmunt** [comment]
I agree @tzarebczan. There was some styling to ensure the qr code had a white border so that it worked with dark mode. This should probably use the `button="link"` style.

**Comment by daovist** [comment]
updated to `button="link"`

**Comment by tzarebczan** [comment]
Working on dark mode now!

**Pull request merged**
