### PR TITLE
Add app closing behavior setting

### PR DESCRIPTION
**Pull request by Ruk33**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: 2220

## What is the current behavior?

When the app is closed, the system tray is always used instead of asking the user if the app should really quit or stay on the system tray.

## What is the new behavior?

A new setting has been added under Advanced Settings to allow the user to control how the quit action should behave. Now the user can control if the app should minimize to the system tray when closed or quit.

image

## Other information

A new setting has been included into lbry-redux: https://github.com/lbryio/lbry-redux/pull/346

### CODE REVIEW

**Comment by seanyesmunt** [comment]
Nice! I'll test this out shortly.

**Comment by seanyesmunt** [comment]
Just tested and (on mac) I see the app being removed from the notification area regardless of the setting.

**Comment by Ruk33** [comment]
Thanks @seanyesmunt , will take a look at it.

**Comment by Ruk33** [comment]
Ok @seanyesmunt I think I got it. Was able to test on MAC with the latest changes and it's working fine on my end.

**Comment by seanyesmunt** [comment]
Testing this now! Sorry for the delay

**Comment by Ruk33** [comment]
Hey @seanyesmunt no worries, please let me know if anything else comes out. Thank you!

**Comment by seanyesmunt** [comment]
@Ruk33 Now I see the app _always_ staying in the notification area regardless of the setting.

**Comment by Ruk33** [comment]
Thank you @seanyesmunt will test it again on the MAC.

**Comment by Ruk33** [comment]
@seanyesmunt I tried to reproduce the issue but on my end seems to work just fine https://imgur.com/gCuPwXP

**Comment by seanyesmunt** [comment]
Hm. I will try again. Maybe I was still running your old version.

**Comment by seanyesmunt** [comment]
@Ruk33 I had a few people try on mac and windows and everyone saw the same issue where it stayed running regardless of the setting.

Do you see it happening in this build too? https://build.lbry.io/app/build-13063_commit-f1c7380/electron/

On any OS

**Comment by Ruk33** [comment]
Hello @seanyesmunt thank you for the link. I tried it on MacOS and the issue persists, although, did you remember to include the changes from lbry-redux (https://github.com/lbryio/lbry-redux/pull/346)? I'm seeing `undefined` on `Developer tools -> Application -> Local Storage -> Notice there is a key: undefined` where it should be `to_tray_when_closed` (this `undefined` happened to me during development and remember I haven't included the lbry-redux change). Please let me know if we could have a build with this redux change to test again. Thanks!

**Comment by seanyesmunt** [comment]
Ah I missed that! I would guess that is the issue. Can you update this line 
https://github.com/lbryio/lbry-desktop/blob/master/package.json#L139

to point at your lbry-redux commit? I just merged it

`210bb80f2c49f6a166a8adc602a68b7490d5d23a`

**Comment by Ruk33** [comment]
Hehe no worries, sure give me 1 sec.

**Comment by Ruk33** [comment]
There we go @seanyesmunt :+1:

**Comment by seanyesmunt** [comment]
Works great. Thank you! Check out https://lbry.com/faq/appreciation because this is great!

**Comment by Ruk33** [comment]
@seanyesmunt thank you for testing and glad you liked it! Will take a look at that page. Regards.

**Pull request merged**
