### PR TITLE
User history

### PR DESCRIPTION
**Pull request by daovist**
See #1009 

Requires [/lbryio/lbry-redux/pull/64](https://github.com/lbryio/lbry-redux/pull/64)

- [x] structures media playback position data by `state.content.[claimId][outpoint]` rather than `state.media[outpoint]`--this will useful down the road when we handle file updates
- [x] remove duplicated data representing a paused file 
- [x] use changes to `state.content.playingUri` to pause video on file opening rather than `state.media.paused`
- [ ] fix UI to not show layover after pausing from opening a file?
- [x] record user history browsing `/show` pages
- [x] add `<UserHistoryPage>` to display a paginated history list with "last viewed" info
- [x] add resume icons to `<FileTile>`s
- [x] add delete icon to `<FileTile>`s shown on `<UserHistoryPage>`
- [ ] style page and tiles

### CODE REVIEW

**Comment by seanyesmunt** [comment]
screen shot 2018-08-02 at 1 07 47 pm

I don't think we need the thumbnail in this view since they would have already seen it when actually navigating to it.

**Comment by seanyesmunt** [comment]
@daovist @skhameneh This is ready for review. I would appreciate some testing, most of the data logic from travis' work stayed, I just changed the ui a bit.

**Comment by daovist** [comment]
I am busy so I only looked at some of the code but the UI looks good. `react-pagination` is most excellent.

I might add a little padding to the top of the darker area but that's not a big deal. Alternating colors (ever so slightly) per item might be nice too, or a hover color change.

**Comment by seanyesmunt** [comment]
@skhameneh 

The app currently doesn't work with the latest `lbry-redux` because I removed the `selectNavLinks` function. Since we have a community PR with `lbry-redux` changes I'm going to merge this, so they can get the app to build properly. I will open another PR if needed to address any comments you have.

**Pull request merged**
