### PR TITLE
7480 upgrade modal is broken (reopen)

### PR DESCRIPTION
**Pull request by Ruk33**
## Fixes

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7480

## What is the current behavior?
- Updates can be downloaded multiple times
- Update nag notification is visible even if the update modal is open
- Users can't disable auto updates

## What is the new behavior?
- Updates will be downloaded once
- Update nag notification is hidden if the update modal is open
- Users can disable auto updates from settings

### Testing information
In order to test these changes, we need to somehow let electron think there is an update.

Create a new file in `dist/electron/webpack/dev-app-update.yml` with the following content:

```yaml
owner: lbryio
repo: lbry-desktop
provider: github
```

Comment line 193 out of file `lbry-desktop\ui\redux\actions\app.js`:

```js
      if (autoUpdateDeclined || isDev) {
        // return; <- here
      }
```

Comment lines from 509 to 517 out `lbry-desktop\node_modules\electron-updater\out\AppUpdater.js`:

```js
    // if (!(await this.isUpdateAvailable(updateInfo))) {
    //   this._logger.info(`Update for version ${this.currentVersion} is not available (latest version: ${updateInfo.version}, downgrade is ${this.allowDowngrade ? "allowed" : "disallowed"}).`);

    //   this.emit("update-not-available", updateInfo);
    //   return {
    //     versionInfo: updateInfo,
    //     updateInfo
    //   };
    // }
```

## PR Checklist

<details><summary>Toggle...</summary>

What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I added a line describing my change to CHANGELOG.md
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

</details>

### CODE REVIEW

**Comment by jessopb** [comment]
This looks ok - need to find time to test a bit more.

**Comment by jessopb** [comment]
I installed this build on mac after deleting app, it immediately offered upgrade to 0.52.5 but pressing the button did nothing.

On linux, pressing the nag button multiple times opening the modal starts multiple downloads. Maybe check if there's a current progress number?

**Comment by Ruk33** [comment]
Thank you @jessopb for the review.

Now that I've set a vm for Linux, I can fully test that end.
With the new changes, no multiple downloads for .deb packages occur and the release notes are being displayed.

Currently, I don't have a mac to test on, could you try again please? Check the console, see if the error message "You must check for an update first" shows up.

**Comment by jessopb** [comment]
Will merge after rebase

**Pull request merged**
