### PR TITLE
Fix and enable 3D viewer

### LINKED ISSUE #4074: Force non-streaming content to wait for download
**Bug**

Some viewers will fail to render content the first time, because some files cant be streamed, you have to wait until the download is completed. 

**To Reproduce**
1. Go to a non-streamable file like `CAD` or `Comicbook`
2. Viewer will try to render the file but it will fail until `download completed`.

**Expected behavior**
Wait for `download completed`, then render the file from the download path not the streaming url.

### PR DESCRIPTION
**Pull request by btzr-io**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [x] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Changes
- Fix 3d viewer styles: see #4035
- Fix minor warnings from three.js
- Remove deprecated themes
- Fix #4074

## Other information

Test this if you can, just to make sure everything works as  expected.

### CODE REVIEW

**Comment by seanyesmunt** [comment]
Thanks for starting on this @btzr-io 

When I try lbry://@mime#6/obj#6, it looks like it tries to render the video player instead of the 3d viewer.

I think https://github.com/lbryio/lbry-desktop/blob/master/ui/redux/selectors/content.js#L190-L192 needs to be moved to the top of the that function. I think `application/octet-stream` is catching for some 3d files.

**Comment by tzarebczan** [comment]
Yea that metadata is before we had the proper one for 3d files. I'd worry less about that one and test with more recent stl /obj samples.

**Comment by seanyesmunt** [comment]
Alright. It worked for other files so I think this is good.

**Comment by btzr-io** [comment]
> When I try `lbry://@mime#6/obj#6`, it looks like it tries to render the video player instead of the 3d viewer.

This issue is not exclusive to 3D files, https://github.com/lbryio/lbry-desktop/issues/4075

I'm still not sure why the app forces `application/octet-stream` files to render as video:
https://github.com/lbryio/lbry-desktop/blob/eaca77d39430fa6f64af054ac3705c687935c18f/ui/constants/claim.js#L14

**Pull request merged**
