### PR TITLE
Fix to open folder containing the log file rather than roaming folder

### PR DESCRIPTION
**Pull request by dyllper**
## PR Checklist
Please check all that apply to this PR using "x":

- [ x ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ x ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type
What kind of change does this PR introduce?

- [ x ] Bugfix
- [ ] Feature
- [ ] Breaking changes (bugfix or feature that introduces breaking changes)
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #1600 

## What is the current behavior?
Clicking "Open Log Folder" will open the "lbry" folder with "lbrynet" highlighted, rather than opening the "lbrynet" folder which contains the log file.

## What is the new behavior?
Clicking "Open Log Folder" will open the "lbrynet" folder that contains the log file.

### CODE REVIEW

**Comment by tzarebczan** [comment]
hey @dyllper, thanks for submitting this PR! We'll have someone review it shortly. Can you also add a changelog entry for this (see previous entries for format). 

Make sure to check out our [contributing document](https://github.com/lbryio/lbry-desktop/blob/master/CONTRIBUTING.md).

Once this is merged, can we send you [some LBC as appreciation](https://lbry.io/faq/appreciation)?

**Comment by dyllper** [comment]
@tzarebczan Updated the Changelog! Sorry about that. Missed that section when I was reading through the CONTRIBUTING.md file.

Thank you for the offer of LBC, but that won't be necessary. Just happy to be able to help out!

**Comment by tzarebczan** [comment]
@dyllper how about a Hacktoberfest t-shirt from LBRY? Just reach out to us at the same address :)

**Comment by seanyesmunt** [comment]
Tested and working good! Thanks @dyllper 🙂

**Pull request merged**
