### PR TITLE
Show warning when opening files externally

### PR DESCRIPTION
**Pull request by zxawry**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #1761

## What is the current behavior?
Clicking the open button, opens file externally with the associated app if they exist, otherwise the file directory is opened.

## What is the new behavior?
Clicking the open button or external links, opens a modal warning user about the consequences. We proceed to open the file or link if user confirms.

## Other information
I'm not sure if it's a breaking change but I renamed `openExternalLink` modal to `openExternalResource`

### CODE REVIEW

**Comment by seanyesmunt** [comment]
@zxawry Thanks for the PR! Ill give it a better look/test tonight! 🙂

**Comment by seanyesmunt** [comment]
This looks good! I'll merge after we release 0.32.0

**Comment by zxawry** [comment]
Thank you, sir!

**Comment by tzarebczan** [comment]
@zxawry , congrats on the merged PR!

Can we show you [some appreciation](https://LBRY.com/faq/appreciation) for the contribution?

**Comment by zxawry** [comment]
Thank you, sir! I'm glad it's merged.

**Pull request merged**
