### PR TITLE
[Not Ready] Add appx target & required files

### PR DESCRIPTION
**Pull request by skhameneh**
Getting the appx published/signed is a WIP.
Blocked on Travis CI issues

### CODE REVIEW

**Comment by skhameneh** [comment]
Hmm, see:
`Error: AppX is supported only on Windows 10 or Windows Server 2012 R2 (version number 6.3+)`

**Comment by seanyesmunt** [comment]
Because we're building on linux?

**Comment by skhameneh** [comment]
See https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264

**Comment by skhameneh** [comment]
For Yarn registry issues, see https://github.com/yarnpkg/yarn/issues/5891

**Comment by skhameneh** [comment]
Closing, see https://github.com/lbryio/lbry-desktop/commit/2dc76d47eafb50a2e73cae6a478b65fa208b1e6a

**Comment by seanyesmunt** [comment]
@skhameneh Now that we are using azure, is there anything else required for adding to the windows store?

**Pull request closed without merging**
