### PR TITLE
Refactor ModalAutoUpdateConfirm into ModalAutoUpdateDownloaded

### PR DESCRIPTION
**Pull request by JakeVdub**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [x] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes 2188

Issue Number: 2188

## What is the current behavior?
Currently there are two different modals being used for essentially the same function, ModalAutoUpdateConfirm and ModalAutoUpdateDownloaded. The only difference between them is ModalAutoUpdateDownloaded would set a boolean to decline auto updates, and then if that is the case ModalAutoUpdateConfirm would be shown instead, that had the same functionality but declining the update didn't change the boolean like UpdateDownloaded did.

## What is the new behavior?
I refactored the two together, and got rid of ModalAutoUpdateConfirm. This was possible by removing the part where UpdateDownloaded set the boolean which was responsible for UpdateConfirm being displayed.

### CODE REVIEW

**Comment by tzarebczan** [comment]
@JakeVdub,  thanks for the PR, we'll get it reviewed soon! Can we show you some [appreciation](https://lbry.com/faq/appreciation)? 

Make sure to check out https://lbry.tech/contribute and sign up for the dev mailing list at the bottom! 

Also, see https://lbry.com/news/hacktoberfest-2019 for the latest Hacktoberfest details.

**Comment by seanyesmunt** [comment]
Thanks for the PR! I will give this a closer look once 0.36.0 is relased.

**Comment by seanyesmunt** [comment]
This looks good! Can you please add a changelog entry to this file? Then it's ready to merge.
https://github.com/lbryio/lbry-desktop/blob/master/CHANGELOG.md

**Comment by tzarebczan** [comment]
@JakeVdub, thanks for the PR! Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the contribution? 

Also, we're giving away some [Hacktoberfest](https://lbry.com/news/hacktoberfest-2019) bonuses and goodies for this month. We'll get it all figured out after you shoot us an email after this is reviewed/merged.

**Pull request merged**
