### PR TITLE
Wallet Page Show Links To Files - Show more of claim name

### PR DESCRIPTION
**Pull request by nestordominguez**
## PR Checklist

Please check all that apply to this PR using "x":

- [x ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x ] Bugfix
- [ x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: https://github.com/lbryio/lbry-desktop/issues/2701

## What is the current behavior?
In wallet page, the recent transactions have the same width in all columns
## What is the new behavior?
Now the column details is more longer than others
## Other information
I fixed a bug generated by className that receive a Boolean value

### CODE REVIEW

**Comment by nestordominguez** [comment]
Yes, I will do today

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by tzarebczan** [comment]
@nestordominguez a friendly poke. I know you had trouble running the app - this should be fixed now. If not, try clearing out your dist folder.

**Comment by nestordominguez** [comment]
Thanks a lot, this solve my problem, I will continue fixing this issue after a break, I was working all day.
________________________________
De: Thomas Zarebczan <notifications@github.com>
Enviado: miércoles, 4 de septiembre de 2019 19:05
Para: lbryio/lbry-desktop <lbry-desktop@noreply.github.com>
Cc: nestordominguez <oscardom80@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [lbryio/lbry-desktop] Wallet Page Show Links To Files - Show more of claim name (#2787)


@nestordominguez<https://github.com/nestordominguez> a friendly poke. I know you had trouble running the app - this should be fixed now. If not, try clearing out your dist folder.

**Comment by oscardominguez80** [comment]
Hi, I did not find other issue related to boolean value in className on the whole page, I have searched in Transaction history too and nothing, if you see this issue in this page then you must press f5 the error is in the previous page

**Comment by seanyesmunt** [comment]
Closing this for now. Feel free to re-open if you have a new solution!

**Pull request closed without merging**
