### PR TITLE
Tagalog Language Fix

### PR DESCRIPTION
**Pull request by iamflorencejay**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes
Changes primary and secondary languages from Filipino to Tagalog

Issue Number: #6286 

## What is the current behavior?
Enum is not good for "fil"

## What is the new behavior?
Now we have tagalog languages supported.

### CODE REVIEW

**Comment by iamflorencejay** [comment]
#6286

**Comment by infinite-persistence** [comment]
This change would require an update in Transifex to rename the translation project from `fil` to `tl`.
Tom, you know how?  Hopefully a rename is possible without having the re-translate everything.

**Comment by iamflorencejay** [comment]
Just copy it all to filipino to tagalog @infinite-persistence

**Comment by iamflorencejay** [comment]
Filipino is based on tagalog anyway @infinite-persistence

**Comment by infinite-persistence** [comment]
Yes, rename/copy was what I was saying.  The concern was on the process in Transifex.  
- The last request to remap the Chinese languages took a while -- not sure what the hiccup was.
- When switching from `ja_JP` to `ja`, there were 2 projects being worked on independently instead of being copied over.

These gave me an impression that Transifex is preventing the copy, but I'm not sure.  Nah, it shouldn't be that inefficient.

**Comment by iamflorencejay** [comment]
> Yes, rename/copy was what I was saying. The concern was on the process in Transifex.
> 
> * The last request to remap the Chinese languages took a while -- not sure what the hiccup was.
> * When switching from `ja_JP` to `ja`, there were 2 projects being worked on independently instead of being copied over.
> 
> These gave me an impression that Transifex is preventing the copy, but I'm not sure. Nah, it shouldn't be that inefficient.

thats sus

**Comment by iamflorencejay** [comment]
#6286

**Comment by iamflorencejay** [comment]
We will need your help for transifex probably @tzarebczan

**Pull request closed without merging**
