### PR TITLE
Differentiate between failed thumbnail url and emtpy url images.

### PR DESCRIPTION
**Pull request by dan1d**
#1808 
Hi, I would need an icon image to be inserted on this issue. Code is ready to be reviewed but I'm missing a second icon, I'm very bad at design, so if anyone can chime in, thanks a lot!

On Failed url:
screenshot from 2018-07-27 17-53-10
On Emtpy url:
screenshot from 2018-07-27 17-53-21

### CODE REVIEW

**Comment by tzarebczan** [comment]
@NetOperatorWibby, think you can give us a hand?

**Comment by NetOperatorWibby** [comment]
@tzarebczan How do I add images to an existing PR?

**Comment by tzarebczan** [comment]
@dan1d where is the image pulling from? I don't see it in the PR.

@NetOperatorWibby since this is a community PR, the branch is on his forked repo. I'd assume you can edit there, or just add the thumbnail to this thread.

**Comment by tzarebczan** [comment]
@dan1d we'd probably want to define the warning thumbnail the same way, right? 

@NetOperatorWibby might just be easier to include a png here (it would be the same size/aspect ratio as the one we provided for the no thumb scenario: https://github.com/lbryio/lbry-desktop/pull/1755/files

**Comment by NetOperatorWibby** [comment]
failed-thumbnail

This should work.

**Comment by dan1d** [comment]
Looks good!
screenshot from 2018-07-30 15-42-57

**Comment by kauffj** [comment]
Above could probably be done in pure CSS. More importantly, it should probably be the error color.

**Comment by NetOperatorWibby** [comment]
+1 for error color but I went with image since the other message is also an image. Is there a unified icon set? It would make sense to take the CSS approach then.

**Comment by NetOperatorWibby** [comment]
error-thumbnail

Used the error color found [here](https://github.com/lbryio/lbry-desktop/blob/master/src/renderer/scss/_vars.scss#L44).

**Comment by dan1d** [comment]
Image updated to red, but should we add them with CSS then ?

**Pull request merged**
