### PR TITLE
Add videos to be played across all pages.

### LINKED ISSUE #579: Keep video playing when navigating from a playing video
When the user navigates from a page with a playing video, this video can be displayed in a picture-in-picture-esque popup, ala Twitch.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

### PR DESCRIPTION
**Pull request by dan1d**
Closes #579 
This PR adds Picture in Picture!
Let me know if any modification is needed

### Todo
- [x] Fix conflicts.
- [ ] Fix navigation issues https://github.com/lbryio/lbry-app/pull/1523#issuecomment-398189947

### Preview

screenshot from 2018-05-26 18-15-28

### CODE REVIEW

**Comment by skhameneh** [comment]
I'll take a look at this (try it out) tomorrow night. 😃 
I ran into a lot of odd cases when investigating this prior.

**Comment by dan1d** [comment]
@skhameneh , i'm working on a commit currently to make it draggable, could you wait please ?

**Comment by dan1d** [comment]
About the new issue, I've fixed on my new commit, I've mistakenly deleted a line, I always test my changes after a commit, I don't know why this one didn't show up that time, anyway fixed.

Now I'm working on make the video draggable: 

screenshot from 2018-05-29 22-21-55

Should the entire video be grabbable?,  currently the dashed part of the video title is the zone where you can drag the video and move it around and only shows up when hovering the video.

A comment from @tzarebczan on discord:
The more I think about it, the grabbable area makes sense - then you can have a close button + button to go back to full view on the show page?
have you considered the "going back to claim page" scenario yet?

What would you suggest @seanyesmunt @skhameneh ?

screenshot from 2018-05-29 22-23-33

**Comment by kauffj** [comment]
My thoughts even though I wasn't asked :grin: :

- It's always good to look at what other well-designed sites do that have spent a lot of time thinking about this (e.g. maybe Netflix or Twitch?)
- While I support draggability, I actually don't consider draggability to be a core requirement for this to be finished. It's a nice-to-have. As an example, Twitch doesn't even appear to support moving the window they provide. 
- If the window is draggable, it ought to retain it's position, even across sessions/restarts. 
- I'd support being able to drag the window via a click and hold anywhere on the entire component
- I'd also support showing a titlebar on mouseover similar to what Twitch always shows on their component. This titlebar could have both a close icon and a move icon. The move icon wouldn't really be any different than clicking-and-holding, it'd just serve as an additional cue.

**Comment by dan1d** [comment]
Hello, I've tried to add a lot of features to this PR but that wouldn't work for me, so I simply went with the basic which is Picture in Picture I think I finished it, you are welcome to test and point me any issues that I didn't figure out.

Thanks @kauffj for pointing me in the right path as we can create a new Issue with your comment to be added when this PR gets merged

**Comment by seanyesmunt** [comment]
Hey @dan1d. I'm really liking how this is looking stylistically. It seems there are a few playback issues. When navigating away, the video stutters, and sometimes it jumps back to the beginning of the video.

**Comment by dan1d** [comment]
I will investigate the jump to start sometimes, im glad you liked the styles!

I hope to finish this by tomorrow!

**Comment by tzarebczan** [comment]
@dan1d per our Discord convo, here's the other bug I found:
Play a video from the home page, go to home page. close the video. go back to same video. The audio is playing twice, no way to stop it. 

Another: Play a video, pause, and navigate away. The video starts playing again in pop out. Should we even be popping out if paused? Repeating this a few times I was able to get the audio to play twice again. 

Question: Should we be popping out if the video ended? We are currently.

**Comment by dan1d** [comment]
Updated code, is not very react but that's the only way that I managed to make the video not to stop show the black screen, let me know what you think, IF it is wrong, then I will need to close this PR as I can't make it work :( 

[Video without black screen](https://www.useloom.com/share/60e25ffd7bfb4aa09b254036efc20d63)

**Comment by seanyesmunt** [comment]
@dan1d I think this could work, I will have to spend some more time digging into it. After a quick test, it looks like the black screen is still there when navigating back to the file page while a video is playing.

**Comment by dan1d** [comment]
Yes, I've leave that issue, I want to know if the solution that I gave to this issue is fine enough to pass before fully get the feature working, thanks @seanyesmunt  for testing it so quickly!

**Comment by tzarebczan** [comment]
These were the last comments from Discord:
[3:32 PM] dan1d: @sean  I found a few issues using vanilla js(context is lost and there are some functions that are called and as the react context is lost it throws an error)
[3:34 PM] dan1d: but on my PR they do work fine as I'm not using react onClick events anymore and just doing vanila video.play() to avoid that exception(edited)

What are the next steps? Are we proceeding down this non-react path or need to explore other options?

**Comment by seanyesmunt** [comment]
Planning on doing a deeper dive to see if this is viable tomorrow.

**Comment by seanyesmunt** [comment]
@dan1d Been pretty busy trying to get bugs fixed for the redesign. I will spend some time on this tonight and actually give you an answer.

**Comment by seanyesmunt** [comment]
@dan1d I super sure on this. I think moving to a modal is fine, but moving back to the video component is where we will run into issues. It might be worth trying to implement the second half of this to see if we run into any issues when going from video overlay => video page?

**Comment by dan1d** [comment]
@seanyesmunt Yes, Moving to the modal does not trigger any error, I may be able to implement the going back to the video, which shouldn't be that difficult, I didn't do that before as I didn't knew if the PR will be accepted with the current code as you know it feels a bit hackish but does the job. 

Thanks for the review!

**Comment by dan1d** [comment]
So moving from overlay to the video by clicking on the overlay icon works correctly.

I think there are 3 issues left:
If you leave the show page(overlayed will show up) or the same video you will get an error.
If you leave the show page and get back to the video page the keyboards callbacks won't work, so we may need to re-hook them.
If the video ends, it should not show the overlay page.

**Comment by seanyesmunt** [comment]
Sorry to leave you hanging @dan1d 

Most of my time has been spent trying to get everything cleaned up for the release of the redesign. I will come back to this after that (hopefully tomorrow)

**Comment by tzarebczan** [comment]
@dan1d said he's still working on finishing this up. Best of luck!

**Comment by seanyesmunt** [comment]
Assigned @skhameneh to determine if this is approach is a viable option.

**Comment by dan1d** [comment]
Hi all, I have been very busy lately, I didn't have enough time to work on this, I have worked on it but still getting a lot of edge cases(events like pressing the bar space does not pause the video)

Fixed: Going back to the video does not show up the black screen anymore
Missing: 
Clicking the same video will make the 2 videos(overlayed and normal screen) to show up
Hookup events

**Comment by seanyesmunt** [comment]
I'm guessing the spacebar issue is due to losing the React hooks after manually moving the video element?

**Comment by dan1d** [comment]
Yes @seanyesmunt

**Comment by skhameneh** [comment]
Hey @dan1d are you still working on this?  
  
I see there's some remaining bugs as well as my earlier comment:
> An entirely new video playback component is created; this creates an interruption of video playback.

Let me know where you're at with this, thanks!

**Comment by dan1d** [comment]
@skhameneh Still missing these two:
Clicking the same video will make the 2 videos(overlayed and normal screen) to show up
Hookup events

**Comment by dan1d** [comment]
Starting again with this one tomorrow morning.

**Comment by dan1d** [comment]
Will do it tonight when i'm on my pc.
Basically I've created a root component sibbling of Router and App for
example, and the video plays there, so I need to work around the styles
size to match the box of the current video div and the overlayed div. That
way i'm not moving around the node elements just manipulating css styles

**Comment by dan1d** [comment]
I also gave another chance to portals but they do remount the video
component.

**Comment by tzarebczan** [comment]
Closing this PR due to inactivity. Issue #579 will be used to track this effort.

**Comment by tzarebczan** [comment]
@dan1d if you could push up your latest changes here, that would still be super helpful!

**Pull request closed without merging**
