### PR TITLE
Add next page cache on channels.

### PR DESCRIPTION
**Pull request by dan1d**
This PR add a prefetch and caches the response when the user visits the channel page.
It should close issue #1851

### CODE REVIEW

**Comment by alyssaoc** [comment]
Thanks for checking out LBRY and the contribution! If you haven't already, please make sure to check out our [contributors guide](https://lbry.tech/contribute).
Can we send you [LBC in appreciation for your work](https://lbry.io/faq/appreciation)

**Comment by dan1d** [comment]
Hi @seanyesmunt, I think we need a new state because we don't want to re-fetch the same page again, going back and forth right ?, so somehow we need to keep track of the page numbers that were already been fetched correct?, currently I've added a call to fetch the page after fetching the current page.  Also I've added a function to fetch the next available page to fetch, for example if you click on the page 1 the first time it will fetch 2 and 3, if you click on the page 2, then It will try to fetch page 4 and 5, that's why the state is needed.

Let me know what do you think!

**Comment by seanyesmunt** [comment]
If we go to page 1 (and fetch page 2/3 in the background), it's ok to fetch them again when we get to that page. What if the content was updated? The main goal with this is to have content appear on the screen faster when going to other pages.

**Comment by dan1d** [comment]
cool @seanyesmunt , I will work on that this night.

**Comment by dan1d** [comment]
Hi @seanyesmunt , I've just updated the code! Thanks for the insight I was overthinking a lot on this one. 👍

**Comment by seanyesmunt** [comment]
@dan1d This is looking better but I still think it can be simplified.

What if `doFetchClaimsByChannel` took a third argument `cacheNextPage`.

If that argument is passed in, you can check if there is an additional page and then call `doFetchClaimsByChannel` from inside the function with the next page.

```
    // Somewhere else
    doFetchClaimsByChannel(uri, 1, true)

    function doFetchClaimsByChannel(uri, page, cacheNextPage) {
      ...
      if (cacheNextPage && page + 1 < totalPages) {
        doFetchClaimsByChannel(uri, page)
      }
    }

```

**Comment by seanyesmunt** [comment]
Doing that would allow opting into this behavior too

**Comment by tzarebczan** [comment]
@dan1d see above, let us know when you think and when you can get this fixed up :)

**Comment by dan1d** [comment]
Today will be ready, I'm going to implement the recursive changes that you
asked!

**Comment by dan1d** [comment]
@seanyesmunt  Code updated! Thanks for the insight on the recursive function, I'm working with Ruby/Ruby on Rails currently so I'm a bit rusty with React/Redux/JS.

**Comment by seanyesmunt** [comment]
@dan1d This is looking good. When testing I see that there are 3 `claim_list_by_channel` calls. I see one for `page: "1"`, one for `page: "1"`, and a third one with no params (I'm not sure where that is coming.)

Could you check it out? I'm not sure if it's your new code or not but we shouldn't be making that third call.

**Comment by seanyesmunt** [comment]
Also I rebased and pulled in the latest changes from master, so you should pull from your fork. You might notice few minor changes from recent PR's

**Comment by seanyesmunt** [comment]
I'm going to close this while I do some repo cleanup. If you plan to finish this up please re-open! I think it would be a great feature in the app.

**Pull request closed without merging**
