### PR TITLE
fixed issue where search bar was being rendered outside of channel co…

### PR DESCRIPTION
**Pull request by consolelogreece**
…ntent tab

## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #3077

### CODE REVIEW

**Comment by seanyesmunt** [comment]
Nice!

**Comment by tzarebczan** [comment]
@consolelogreece, thanks for the PR! Congrats on the first one here :)

Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the contribution? 

Also, we're giving away some [Hacktoberfest](https://lbry.com/news/hacktoberfest-2019) bonuses and goodies for this month.

**Comment by consolelogreece** [comment]
@tzarebczan thank you! I hadn't heard of lbry until today, I love the concept. 

How do I claim the hacktoberfest stuff?

**Comment by tzarebczan** [comment]
See the FAQ I linked above: https://lbry.com/faq/appreciation

**Pull request merged**
