### PR TITLE
Add GitHub pull request template

### PR DESCRIPTION
**Pull request by pushkyn**

### CODE REVIEW

**Comment by seanyesmunt** [comment]
@pushkyn Thanks for the PR! 🙂 

I think there is one other case where a PR is related to an issue, but it doesn't mean the issue is closed when it's merged. ex: #2024 

Maybe `Related` or `For`?

**Comment by pushkyn** [comment]
@seanyesmunt you are right, I changed the text a little

**Comment by seanyesmunt** [comment]
@pushkyn Looks great. Thanks for the PR!

**Comment by seanyesmunt** [comment]
Reach out to us at hello@lbry.io so we can [send you some LBC as appreciation](https://lbry.io/faq/appreciation) and get you a t-shirt for Hacktoberfest 🙂

**Pull request merged**
