### PR TITLE
Re-add ability to export transactions 

### LINKED ISSUE #4793: Export Wallet History For Taxation Purposes
**Is your feature request related to a problem? Please describe.**
Manually keeping track of your wallet history is completely impractical, especially when you're a large creator with close to 3000 pages of your wallet. If I could export the history then I could easily automate the process.

**Describe the solution you'd like**
A button to export the transaction history, a CSV would probably be good enough, preferably being able to export based on the filtering already present on the wallet page of the app. So just supports, just tips, so and so forth.

**Describe alternatives you've considered**
Manually counting 3000 pages of tips is going to take a while.

**Additional context**
I would like to see this addressed before governments start taking notice of how much unaccounted for money is flowing through this platform. I'm 99% sure this used to be available, I'm not sure why it was removed.

### PR DESCRIPTION
**Pull request by infinite-persistence**
## Issue
Closes #4793 [Export Wallet History For Taxation Purposes](https://github.com/lbryio/lbry-desktop/issues/4793)

_Requires lbry-redux update_

## Screenshots
- Start:
    - image
- Fetching:
    - image
- In the unlikely-event that the fetched data couldn't be parsed:
    - image
- Fetched and file is ready:
    - image

### CODE REVIEW

**Comment by tzarebczan** [comment]
Took about a minute on my wallet, will try some other large ones. Not bad...

I noticed support_list is called - is that data used anywhere? we shouldn't need anything outside of transaction list. 

99K may be too small for some of the larger creators, so let's add another 9. We'll deal with performance issues/run manually for others as needed.

**Comment by infinite-persistence** [comment]
> _I noticed support_list is called - is that data used anywhere? we shouldn't need anything outside of transaction list._

Wanted to ask that as well. @seanyesmunt, safe to remove `doFetchSupports`? 

```javascript
export function doFetchTransactions(page = 1, pageSize = 99999) {
  return dispatch => {
    dispatch(doFetchSupports());   // <---- ??
    dispatch({
      type: ACTIONS.FETCH_TRANSACTIONS_STARTED,
    });

    Lbry.transaction_list({ page, page_size: pageSize }).then(result => {
      dispatch({
        type: ACTIONS.FETCH_TRANSACTIONS_COMPLETED,
        data: {
          transactions: result.items,
        },
      });
    });
  };
}
```

**Comment by infinite-persistence** [comment]
> _Took about a minute on my wallet, will try some other large ones. Not bad..._

- Pondering if we need to add notification (desktop) or toast (web) for "Transactions file ready for download".
- "Fetching data..." would then need to be something like "Fetching data; check back here later".

**Comment by infinite-persistence** [comment]
`UPDATE`
- Removed support-fetching
- Bumped pageSize

**Comment by infinite-persistence** [comment]
`UPDATE`
- Resolve conflict in changelog

`REMINDER`
- Another lbry-redux merge is required.

**Pull request merged**
