### PR TITLE
Add Language Support: German

### PR DESCRIPTION
**Pull request by fi-do**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: None

## What is the current behavior?
Supports English, Polish and Indonesian language.

## What is the new behavior?
Supports English, Polish, Indonesian and German language.

## Other information
I have added the German language.

### CODE REVIEW

**Comment by tzarebczan** [comment]
@fi-do , thank you for the PR! We are currently working out a few other kinks with the existing languages, but maybe we can get this added in the meantime as well. Were these done through transifex? See https://docs.google.com/document/d/1xhoiakNNpWIocPmkbW_JUGu98cBaYoMMAeGFDrP44LU for instructions (requires us to send a password, @jsigwart can follow up).

Can we show you some [appreciation](https://lbry.com/faq/appreciation) for this effort?

**Comment by fi-do** [comment]
@tzarebczan , thanks for your reply. At this point, i didn't know Transifex. I have edited manually and would be happy if it contributes to your project. So in the future, Transifex should be used for the translations?

**Comment by jsigwart** [comment]
We're using Transifex and we have added your translations, @fi-do. Please check out https://www.transifex.com/lbry/lbry-desktop/language/de_DE/ and submit a request to translate as there are more strings left. Thank you for your help!

**Comment by fi-do** [comment]
@jsigwart , thank you. I joined the team on transifex.

**Comment by jsigwart** [comment]
Added most recent changes from Transifex.

**Pull request merged**
