### PR TITLE
Center livestream viewing mode

### PR DESCRIPTION
**Pull request by saltrafael**
## PR Checklist

Please check all that apply to this PR using "x":

- [X] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [X] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

### CODE REVIEW

**Comment by seanyesmunt** [comment]
Screen Shot 2021-04-26 at 2 48 31 PM

This causes issues on large screens that aren't very tall. If you make the window full width, but shrink the height, the `max-height` on the video element forces the controls to disappear.

**Comment by saltrafael** [comment]
> This causes issues on large screens that aren't very tall. If you make the window full width, but shrink the height, the `max-height` on the video element forces the controls to disappear.

Hmm I just attempted this on Odysee and got the same:



So looks like this was already an unnoticed issue?

**Comment by tzarebczan** [comment]
For this one, we'd want it to match the regular content page where the video is centere along with chat, not defaulting to theatre mode.

**Comment by saltrafael** [comment]
> For this one, we'd want it to match the regular content page where the video is centere along with chat, not defaulting to theatre mode.

Oh I see, I was taking inspiration from other streaming platforms that default to it and also since there is only the chat and the content on screen I thought it would make sense to just "fill" the screen with it, also did you check the issue sean mentioned about changing the height of the screen? It still happens on odysee or lbrytv

**Comment by tzarebczan** [comment]
Let's just match what's on the regular content pages for now, and that will take care of Sean's issue also. Do you want to do it under this PR or want me to close it?

**Comment by saltrafael** [comment]
So just make it center like this?

**Comment by tzarebczan** [comment]
And probably connect the chat on the left, and center those two items together on the page.

**Comment by tzarebczan** [comment]
And please resolve the conflicts too

**Comment by tzarebczan** [comment]
Not sure why this was closed - can we rebase and try to get it in again?

**Pull request merged**
