### PR TITLE
Comic-book reader

### PR DESCRIPTION
**Pull request by btzr-io**
> # WIP...
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #1377

## What is the current behavior?
There is no viewer for comic book archives

## What is the new behavior?
A simple viewer for comic book archives (CBR, CBT, CBZ, CB7)

### CODE REVIEW

**Comment by btzr-io** [comment]
I'm not sure if I should be adding this files inside the static folder:
https://github.com/lbryio/lbry-desktop/tree/comicbook-reader/static/webworkers

> ES module and webworker bundle, ES module part is your interface to talk to library, use it like any other module, webworker bundle lives in libarchive.js/dist folder so you need to make sure that it is available in your public folder since it will not get bundled if you're using bundler (it's all bundled up already) and specify correct path to Archive.init() method

https://github.com/nika-begiashvili/libarchivejs#how-to-use

**Comment by btzr-io** [comment]
There still some work to do on the repo side: https://github.com/btzr-io/Villain

**Comment by btzr-io** [comment]
The viewer should also work on the website, but I'm not sure how to enable it yet :stuck_out_tongue:

**Comment by seanyesmunt** [comment]
This is awesome! We still have to make some changes to handle viewing any non audio/video content on lbry.tv.

Why does this need a webworker?

**Comment by btzr-io** [comment]
@seanyesmunt The worker is required by `libarchivejs` and it's for the extraction process (decompression of the archive)
https://github.com/btzr-io/Villain#webworker

**Comment by seanyesmunt** [comment]
@kauffj Do you know if could be any issues with adding this? https://github.com/nika-begiashvili/libarchivejs

**Comment by seanyesmunt** [comment]
@btzr-io I think this is fine. Can you just add a comment above the static scripts that explains why they are there?

**Comment by kauffj** [comment]
I only took a quick glance, but I don't see why we couldn't add libarchivejs. It's worth considering: 1) whether archive support should be added to the SDK and 2) how this will work on the web, but neither are blocking considerations.

**Comment by btzr-io** [comment]
@seanyesmunt  in this [file](https://github.com/lbryio/lbry-desktop/blob/comicbook-reader/static/webworkers/worker-bundle.js) ?

**Pull request merged**
