### PR TITLE
Make the volume control remember if muted

### PR DESCRIPTION
**Pull request by nestordominguez**
## PR Checklist

Please check all that apply to this PR using "x":

- [ x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: https://github.com/lbryio/lbry-desktop/issues/2361

## What is the current behavior?
At this moment when you mute some video and go to other video the muted option is losing

## What is the new behavior?
with this new pr, when you set mute in some video and go to other video, this new video will be settled with older muted option

### CODE REVIEW

**Comment by tzarebczan** [comment]
Thanks for the PR!! We are going to be switching out this video player soon, but we'll reuse this code. Will leave open for now. It should just remember the overall volume, not just muted state - want to add that?

**Comment by nestordominguez** [comment]
I see that the overall volume state is saved, but I can't change to a new volume

**Comment by tzarebczan** [comment]
That's fine, it's broken in this player. So do we really need a separate state for muted or is 0 for volume good enough?

**Comment by nestordominguez** [comment]
We need the two state one for volume and other for muted, since in the player it is taken as two different properties

**Comment by nestordominguez** [comment]
The properties for volume is a number and for muted is boolean

**Comment by seanyesmunt** [comment]
Thanks for the PR! Tested and working good.

**Pull request merged**
