### PR TITLE
Fix language setting

### PR DESCRIPTION
**Pull request by tzarebczan**
Seems to work locally when building.

### CODE REVIEW

**Comment by seanyesmunt** [comment]
Tested and working. Nice fix!

**Comment by kauffj** [comment]
@seanyesmunt do you understand why `__static` didn't work here? Isn't `__static` designed to handle this? @tzarebczan said this broke it in dev mode.

**Comment by kauffj** [comment]
"Read the code, Jeremy" - @seanyesmunt

**Comment by seanyesmunt** [comment]
I am curious to what code you read to understand this. I'm still not sure why it wasn't working with `__static`

**Pull request merged**
