### PR TITLE
Language cleanup + additional languages

### LINKED ISSUE #5646: Add more completed language translations
- [ ] Wanted to check if the following languages are intentionally excluded for some technical reasons.  They are either fully translated, or was fully translation at one point in the past.
    - `filipino`
    - `vietnamese`
    - `afrikaans`
    - `thai` - translator complained
    - `japansese (ja)`

- [ ] There is a duplicate for japanese in Transifex.  I think we can remove `ja_jp`, unless it's for something else?

### PR DESCRIPTION
**Pull request by infinite-persistence**
## Issue
Closes #5646[: Add more completed language translations ](https://github.com/lbryio/lbry-desktop/issues/5646)

## Changes
- Simplify language-related code (see commit messages for walkthrough)
- Added Japanese, Afrikaans, Filipino, Thai and Vietnamese

## Review Notes
- Might want to have a second look on the Homepage Selector.  From the live site, is it using `zh`?  Anyway, I don't think it is impacted by the refactoring, but worth a look.

### CODE REVIEW

**Comment by infinite-persistence** [comment]
## Back to Draft
Found a piece of hardcoded stuff in `i18n.js`.
```
export function __(message, tokens) {
  const language = localStorageAvailable
    ? window.localStorage.getItem('language') || 'en'
    : window.navigator.language.slice(0, 2) || 'en';
  if (!isProduction) {
    IS_WEB ? saveMessageWeb(message) : saveMessageDesktop(message);
  }
```
It should use `getDefaultLanguage` instead of slicing.  No issues in Desktop, but how do we handle such imports for both Desktop and Web?

**Comment by jessopb** [comment]
I like this - I'll get to it shortly.

**Comment by jessopb** [comment]
I asked discord to test it. I like it - it looks really elegant.

**Comment by infinite-persistence** [comment]
`--- Update 987c917 ---`
- Rebased to flx conflict.
- Added string corrections and additions reported from Translators.

**Comment by jessopb** [comment]
Ran it on mac and linux - seemed to work great!

**Review by jessopb — APPROVED** [review]
This is much better, thanks!

**Pull request merged**
