### PR TITLE
Changed how 'Blocked channels' are displayed on settings and a typo

### PR DESCRIPTION
**Pull request by TigerxWood**
Problems solved (second attempt):
A. Small typo for <div className="card__title card__t itle--deprecated"> (extra space in the word **t itle**)

B. More details about problems with languages:
1. The word blocked has two forms in other languages (one for plural and one for singular) and therefore must be put together with channel and channels words. Currently it can be translated in only one form.

2. In the case there are no blocked channels there is no need to show the 0 value and is more elegant the message 'You do not have blocked channels'

3.  The link to manage the channels should not be visible in the case that there is no channel blocked, because there is no channel that need to be managed.

And about your statement: "Your change would make it harder for other languages to change this sentence." 

It's quite the opossite, it's very clear and easy. They just have to translate (with examples in Romanian):
'%count% %channels%. ',     (leave it as it is)
'You don't have' = 'Nu aveți'
'You have' = 'Aveți'
'blocked channel' = 'canal blocat'
'blocked channels' = 'canale blocat**e**'  (see the change for plural forms for the word blocked, not only for channels word?)

I hope this time I explained better the need for the changes.
Thanks

Messages displayed:
Case with 0 blocked channels: You don't have blocked channels. (No Manage button displayed)
Case with 1 blocked channel: You have 1 blocked channel. **Manage** (manage link)
Case with 2 or more blocked channels: You have 2 blocked channels. **Manage** (manage link)

## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number:

### CODE REVIEW

**Comment by seanyesmunt** [comment]
@tiger5226 I will merge the typo fix, but not the other fix. Please stop opening up PR's to change that string. Your change would require languages to translate multiple half-strings, instead of one single sentence.

**Comment by TigerxWood** [comment]
Did you read my explanations? I give you more details why this is wrong as it is now.

**Comment by TigerxWood** [comment]
And you sent the message to the wrong guy. I am TigerxWood not tiger5226.
The first time, some weeks ago, whe I maded the first change I knew there will be these problems and I suggested a more generic way, to just put "Blocked channels: %countchannels%", but you changed that and entered in more details with singular, plural forms. As we know the devil is in details. So, now if you want that details, then you need to make it right for all languages.

**Comment by seanyesmunt** [comment]
Whoops.

I'm sorry I haven't given this as much time as I should. You are right, this should work for all languages, even if it makes the code more complex. We can merge this. Thank you for staying persistent!

**Comment by TigerxWood** [comment]
Well, thank you, I almost worried about your decisions. That's why my name is tiger, because I have eyes of tiger and I don't back up when I know I'm right. Have a good day and I hope to see you soon with new bugs resolved.
Currently there are many half translated strings all over the app and lbry.tv, like those from #4202 and #4173 and I try to investigate them all because that make the application look bad, like a half finished app and not so proffesional.

**Comment by infinite-persistence** [comment]
Hey guys,

I'm confused as it seems to be going backwards.  Isn't concatenating strings a bad approach, as it assumes all languages follow the same word structure?  Japanese (when supported) will not work due to this split as the order is almost always different.  I'm sure there are other affected languages as well.

      "you have 6 blocked channels" --> "6つのブロックされたチャンネルがあります"

Another odd things is that `"%count% %channels%. ": "%count% %channels%. "` will now appear in the next translation batch. I'm pretty sure translators won't know what to do with it and will just paste the same thing.  Since it was noted to be left as is, it feels like a waste of time for the translators.

The old `"You have %count% blocked %channels%.": "You have %count% blocked %channels%."` is a better solution as they can move the variables around.  

**Solution**
If the issue being solved here is about the plural form, the proper solution is to just have two strings, with _%channels%_ removed.
`"You have %count% blocked channels": "You have %count% blocked channels"`
`"You have %count% blocked channel": "You have %count% blocked channel"`
If a particular language doesn't have plural forms (e.g. ms), then both strings will simply be translated to the same value.  This will cover all cases, from a translator's point of view.

**Comment by TigerxWood** [comment]
Yes, it seems some languages put the number first. I fixed the problem. Now all languages should be fine and easy to translate.

**Pull request merged**
