### PR TITLE
Open ZoomableImage viewer when clicking on the image

### PR DESCRIPTION
**Pull request by togekk1**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number:

### CODE REVIEW

**Comment by tzarebczan** [comment]
Thanks for PR, we'll get a review on this soon! 

After that, can we show you some [appreciation](https://lbry.com/faq/appreciation) for the contribution?

**Review by seanyesmunt — CHANGES_REQUESTED** [review]
We already have a button to open a file externally. This should probably use the `ZoomableImage` component instead. Then it will work on web too

**Comment by togekk1** [comment]
> We already have a button to open a file externally. This should probably use the `ZoomableImage` component instead. Then it will work on web too

You're right. I'll submit another commit later. Thanks!

**Comment by seanyesmunt** [comment]
Works great! Thanks

**Pull request merged**
