### PR TITLE
Added options for Arch Linux in the download options

### PR DESCRIPTION
**Pull request by kcseb**
Added the AUR URLs to the default download options under "Alt. Linux Build"

Before - http://hfimg.pw/i/g4py9.png
After - http://hfimg.pw/i/ohzrm.png

### CODE REVIEW

**Comment by seanyesmunt** [comment]
How is the LBRY app being added to that site?

**Comment by kcseb** [comment]
It is the AUR (Arch User Repository). 
Currently, there is only .tar.gz and .deb versions of the LBRY Application for Linux. Users of Arch Linux can use the AUR to clone and build the application with a simple (packagebuild/PKGBUILD) script. 
The script installs dependencies and the application for them. Think of it like make and make install, but far more simple.

**Comment by seanyesmunt** [comment]
What do we have to do to upload to that site?

**Comment by kcseb** [comment]
There are instructions on the Wiki page. 
https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages

Create an AUR account, add your SSH key to your profile, and use some Git commands to commit and push to the AUR repositories.

**Comment by seanyesmunt** [comment]
Do you know if that process can be automated?

**Comment by kcseb** [comment]
No, not really as the AUR is user-maintained and the maintainers/author of each repository have to manually commit and push the updates. 

I, along side others on the AUR would gladly keep the `lbry-app-release` repository up to date as new LBRY application versions are released.

**Comment by TimurKiyivinski** [comment]
Hi, I am the maintainer for the [current AUR package](https://aur.archlinux.org/packages/lbry-app-bin/) and have been faithfully doing so for over a year. I received a merge request for your package, `lbry-app-release`, @kcseb .

@seanyesmunt yes it can technically be automated if I were to listen for releases on LBRY then run a script to update the package. I haven't had time to look into this. As of right now however, I manually update and test the packages locally.

I will happily add anyone from LBRY as a maintainer on the AUR for managing releases too.

**Comment by tzarebczan** [comment]
@seanyesmunt I'd support adding this along with the flatpak support in a community maintained section of the readme: https://flathub.org/apps/details/io.lbry.lbry-app

**Comment by seanyesmunt** [comment]
Was planning on bringing that up today. Yeah, I think it would be a great idea to have another table below the current downloads table titled "Community-maintained releases" With a note describing it.

**Comment by tzarebczan** [comment]
We just need to figure out how we want to support the autoupdate process for them. Right now, they would get prompted to download the deb file. Maybe we can disable this for flatpaks/aurs. 

Someone also mentioned making a ppa for the deb, and the update process would also be a bit less painful. 

The longer-term autoupdate process would include either appimage or snaps, as this is what electron builder currently supports.

**Comment by tzarebczan** [comment]
I'll get a new community maintained section created for Flatpak/AUR builds. I'd ask @TimurKiyivinski / @kcseb to look after the AUR package and @iuyte for the flatpak (also asked @choffee as he just submitted one for 0.22.2 - https://github.com/flathub/io.lbry.lbry-app/pull/9)

I'll open a separate issue for dealing with auto update and maybe a community member can look into it.

**Comment by kcseb** [comment]
@TimurKiyivinski if you'd like to assign me as a co-maintainer on the AUR, my handle is the same as here on GitHub (kcseb) Thank you.

**Comment by kcseb** [comment]
@TimurKiyivinski 
We've updated to

**Comment by TimurKiyivinski** [comment]
@kcseb I've added you as a co-maintainer, but please do not attempt hijacking packages any more.

**Pull request merged**
