### PR TITLE
Open in desktop

### PR DESCRIPTION
**Pull request by btzr-io**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I added a line describing my change to CHANGELOG.md
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #6703, #6659 
Changelog update: #6735

# Web -> Desktop

image

### CODE REVIEW

**Comment by kauffj** [comment]
I like the intent of this but we're trying to keep Odysee and LBRY Desktop separately. Please discuss with me over chat.

**Comment by btzr-io** [comment]
@kauffj  When I open an external 'lbry://' link on the browser, the desktop app doesn't resolve it. This PR also fixes that bug.

**Comment by btzr-io** [comment]
Changelog update: #6735

**Comment by btzr-io** [comment]
Can someone review this ?

**Comment by roylee17** [comment]
> Can someone test or review this ?

Thanks for your contribution. 
I'd recommend @jessopb for reviewing.

**Review by kauffj — COMMENTED** [review]
The code looks fine but I still have concerns about introducing this element on Odysee, where many users will not have LBRY Desktop.

What's the UX like when the user does not have the desktop app installed? Is there a way we can explain to those users what this feature does?

**Comment by btzr-io** [comment]
> What's the UX like when the user does not have the desktop app installed? 

I think is ignored if there is no protocol handler registered.

> Is there a way we can explain to those users what this feature does?

I'm not sure if is possible to detect if the link was open or check for a registered protocol handler.  I'll give it a try.

**Comment by btzr-io** [comment]
> What's the UX like when the user does not have the desktop app installed?

Here are some initial ideas:

- Show a modal to inform the user about the desktop app
- Open a link directly to the lbry website

**Comment by btzr-io** [comment]
> Open a link directly to the lbry website: https://lbry.com/get

I think this makes more sense ^^

**Comment by btzr-io** [comment]
This requires more additional work, I removed all the UI changes #6779

**Comment by snakyjake1** [comment]
This half way works.  I'll explain...

I want the LBRY Desktop app to accept a parameter for a link, and go to the link.

# Functionality
## Function 1:  Protocol ("LBRY://")
In Windows Run, I want the associated program to open the link:
image

## Function 2:  LBRY.exe Parameter ("c:\program files\LBRY\LBRY.exe %1")
image

# Functional Test 1
LBRY Desktop running.

## Test 1A
Failed test.
In both functions, LBRY Desktop receives focus.  But, LBRY Desktop does not go to the link. 

## Test 1B
In both functions, LBRY Desktop receives focus.  But, LBRY Desktop does not go to the link. 

# Functional Test 2
LBRY Desktop not running.

## Test 2A
Passed test.
In both functions, LBRY Desktop receives focus and LBRY Desktop goes to the link. 

## Test 2B
Passed test.
In both functions, LBRY Desktop receives focus and LBRY Desktop goes to the link.

**Comment by btzr-io** [comment]
@snakyjake1 Did you try https://github.com/lbryio/lbry-desktop/releases/tag/untagged-aa3ae8f9162b42aace2a ?

**Comment by snakyjake1** [comment]
> Did you try https://github.com/lbryio/lbry-desktop/releases/tag/untagged-aa3ae8f9162b42aace2a ?

@btzr-io I couldn't get your link to work.

**Comment by btzr-io** [comment]
@snakyjake1 Whats your current desktop version ? Where Test 1A, Test 1B run using v0.51.0-rc.2 ?

**Pull request closed without merging**
