### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vyaspranjal33**
added LICENSE badge

### CODE REVIEW

**Comment by seanyesmunt** [comment]
@vyaspranjal33 Thanks for the PR! 🙂 

Maybe this should be the very first badge we have in the readme. I think this is more important than the other ones.

**Comment by vyaspranjal33** [comment]
@seanyesmunt  are u merging ?

**Comment by tzarebczan** [comment]
Can you make this the first badge as Sean suggested? Thanks again for the PR!

**Comment by vyaspranjal33** [comment]
@tzarebczan  changes have been made as per suggestion @seanyesmunt

**Comment by seanyesmunt** [comment]
Thanks @vyaspranjal33

Can you rebase your PR so there is only one commit? Then we can merge.

**Comment by vyaspranjal33** [comment]
@seanyesmunt please close this PR because i am submitting a new PR from my master branch

**Pull request closed without merging**
